/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author LionKeriot
 */
public class About extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(About.class.getName());

    /**
     * Creates new form About
     */
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(350, 250);
        setLocationRelativeTo(null); // Centra en pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jLabelCurso = new javax.swing.JLabel();
        jLabelSobre = new javax.swing.JLabel();
        jLabelFuentes = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelNombre.setText("Full name: Rubén Gómez Hernández");
        getContentPane().add(jLabelNombre);
        jLabelNombre.setBounds(10, 60, 290, 16);

        jLabelCurso.setText("Course: 2º Desarrollo de aplicaciones Multiplataforma");
        getContentPane().add(jLabelCurso);
        jLabelCurso.setBounds(10, 80, 290, 16);

        jLabelSobre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSobre.setText("About...");
        getContentPane().add(jLabelSobre);
        jLabelSobre.setBounds(150, 10, 70, 30);

        jLabelFuentes.setText("Sources used: yt-dlp, ffmpeg, ffprobe, copilot, stack overflow");
        getContentPane().add(jLabelFuentes);
        jLabelFuentes.setBounds(10, 100, 340, 16);

        jButtonSalir.setText("Exit");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir);
        jButtonSalir.setBounds(140, 150, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose(); // Cierra el diálogo
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelCurso;
    private javax.swing.JLabel jLabelFuentes;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSobre;
    // End of variables declaration//GEN-END:variables
}
