
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author LionKeriot
 */
public class DownloadComplete extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DownloadComplete.class.getName());
    private File downloadFile;
    /**
     * Creates new form DescargaCompletada
     */
    public DownloadComplete(java.awt.Frame parent, boolean modal, File downloadFile) {
        super(parent, modal);
        initComponents();
        this.downloadFile = downloadFile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTerminada = new javax.swing.JLabel();
        jButtonReproducir = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Download Complete!");
        setModal(true);
        getContentPane().setLayout(null);

        jLabelTerminada.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Documents\\NetBeansProjects\\YouDownloadDefinitivo\\resources\\icons\\icons8-checkmark-120.png")); // NOI18N
        jLabelTerminada.setText("DOWNLOAD COMPLETED!");
        getContentPane().add(jLabelTerminada);
        jLabelTerminada.setBounds(0, 20, 290, 120);

        jButtonReproducir.setText("Play it!");
        jButtonReproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReproducirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReproducir);
        jButtonReproducir.setBounds(60, 160, 75, 23);

        jButtonSalir.setText("Exit");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir);
        jButtonSalir.setBounds(150, 160, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReproducirActionPerformed
        if (downloadFile != null && downloadFile.exists()) {
            try {
            Desktop.getDesktop().open(downloadFile);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Couldn't open file: " + e.getMessage());
        }
        } else {
            JOptionPane.showMessageDialog(this, "File not found.");
        }
    }//GEN-LAST:event_jButtonReproducirActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReproducir;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelTerminada;
    // End of variables declaration//GEN-END:variables
}
