
import java.util.List;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author LionKeriot
 */
public class MediaLibrary extends javax.swing.JPanel {
    private final PantallaPrincipal principal;
    private final JPanel panelOriginal;
    private final List<InformacionDescargas> listaRecursos;
    private InformacionDescargasTableModel tableModel;
    
    public MediaLibrary (PantallaPrincipal principal, JPanel panelOriginal, List<InformacionDescargas> listaRecursos){
        this.principal = principal;
        this.panelOriginal = panelOriginal;
        this.listaRecursos = listaRecursos;
        
        initComponents();
        tableModel = new InformacionDescargasTableModel(listaRecursos);
        jTableMedia.setModel(tableModel);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneMedia = new javax.swing.JScrollPane();
        jTableMedia = new javax.swing.JTable();
        jComboBoxFiltro = new javax.swing.JComboBox<>();
        jButtonFiltrar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setLayout(null);

        jTableMedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneMedia.setViewportView(jTableMedia);

        add(jScrollPaneMedia);
        jScrollPaneMedia.setBounds(0, 0, 930, 500);

        jComboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBoxFiltro);
        jComboBoxFiltro.setBounds(110, 530, 72, 22);

        jButtonFiltrar.setText("Filter");
        add(jButtonFiltrar);
        jButtonFiltrar.setBounds(200, 530, 72, 23);

        jButtonVolver.setText("Return");
        jButtonVolver.setName(""); // NOI18N
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        add(jButtonVolver);
        jButtonVolver.setBounds(380, 530, 75, 23);

        jButtonEliminar.setText("Delete");
        add(jButtonEliminar);
        jButtonEliminar.setBounds(290, 530, 72, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        principal.setContentPane(panelOriginal);
        principal.revalidate();
        principal.repaint();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxFiltro;
    private javax.swing.JScrollPane jScrollPaneMedia;
    private javax.swing.JTable jTableMedia;
    // End of variables declaration//GEN-END:variables
}
