
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author LionKeriot
 */
public class MediaLibrary extends javax.swing.JPanel {
    private final PantallaPrincipal principal;
    private final JPanel panelOriginal;
    private final List<InformacionDescargas> listaRecursos;
    private InformacionDescargasTableModel tableModel;

    
    public MediaLibrary (PantallaPrincipal principal, JPanel panelOriginal, List<InformacionDescargas> listaRecursos){
        this.principal = principal;
        this.panelOriginal = panelOriginal;
        this.listaRecursos = listaRecursos;
        
        initComponents();
        tableModel = new InformacionDescargasTableModel(listaRecursos);
        jTableMedia.setModel(tableModel);
        
        javax.swing.table.TableRowSorter<InformacionDescargasTableModel> sorter = new javax.swing.table.TableRowSorter<>(tableModel);
        jTableMedia.setRowSorter(sorter);
        
        
        initFiltroComboBox();
        initBusqueda();
        initJlist();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneMedia = new javax.swing.JScrollPane();
        jTableMedia = new javax.swing.JTable();
        jLabelFiltro = new javax.swing.JLabel();
        jComboBoxFiltro = new javax.swing.JComboBox<>();
        jButtonEliminar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabelSearch = new javax.swing.JLabel();
        jTextFieldBusqueda = new javax.swing.JTextField();
        jScrollPaneTextFilter = new javax.swing.JScrollPane();
        jListTextFilter = new javax.swing.JList<>();

        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setLayout(null);

        jTableMedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneMedia.setViewportView(jTableMedia);

        add(jScrollPaneMedia);
        jScrollPaneMedia.setBounds(0, 0, 930, 220);

        jLabelFiltro.setText("Filter by:");
        add(jLabelFiltro);
        jLabelFiltro.setBounds(10, 230, 70, 30);

        jComboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltroActionPerformed(evt);
            }
        });
        add(jComboBoxFiltro);
        jComboBoxFiltro.setBounds(130, 230, 120, 30);

        jButtonEliminar.setText("Delete");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        add(jButtonEliminar);
        jButtonEliminar.setBounds(400, 230, 120, 30);

        jButtonVolver.setText("Return");
        jButtonVolver.setName(""); // NOI18N
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        add(jButtonVolver);
        jButtonVolver.setBounds(690, 230, 120, 30);

        jLabelSearch.setText("Search by text:");
        add(jLabelSearch);
        jLabelSearch.setBounds(10, 270, 80, 30);
        add(jTextFieldBusqueda);
        jTextFieldBusqueda.setBounds(130, 270, 120, 30);

        jListTextFilter.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneTextFilter.setViewportView(jListTextFilter);

        add(jScrollPaneTextFilter);
        jScrollPaneTextFilter.setBounds(10, 310, 240, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        principal.setContentPane(panelOriginal);
        principal.revalidate();
        principal.repaint();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
       // Obtiene la fila seleccionada
       Object[] opciones = {"Yes", "No"};
        int filaSeleccionada = jTableMedia.getSelectedRow();
        
        // Asignamos una variable al recurso que vamos a eliminar.
        if (filaSeleccionada >=0) {
            InformacionDescargas  recursoEliminar = listaRecursos.get(filaSeleccionada);
        
       // Pedimos confirmación
       int confirmacion = javax.swing.JOptionPane.showOptionDialog(this,"Are you sure you want to delete '" 
            + recursoEliminar.getNombreArchivo(),"Confirm Deletion",
            javax.swing.JOptionPane.YES_NO_OPTION, // Tipo de opción
            javax.swing.JOptionPane.QUESTION_MESSAGE, // Icono de pregunta
            null, // No usar icono custom
            opciones, // Array de Strings a mostrar en los botones
            opciones[0] // Opción por defecto ("Yes")
            );
       
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            java.io.File archivo = new java.io.File(recursoEliminar.getRutaAbsoluta());

            if (archivo.delete()) {
                listaRecursos.remove(filaSeleccionada);
                tableModel.fireTableDataChanged();
                javax.swing.JOptionPane.showMessageDialog(this, "File deleted successfully.", "Success!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } else {
                    // Error al eliminar del disco (ej: el archivo no existe o permisos insuficientes)
                    javax.swing.JOptionPane.showMessageDialog(this, "Error: File could not have been deleted. Check the log.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
            } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a file to delete", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jComboBoxFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltroActionPerformed

    
    @SuppressWarnings("unchecked")
    javax.swing.table.TableRowSorter<InformacionDescargasTableModel> sorter = 
    (javax.swing.table.TableRowSorter<InformacionDescargasTableModel>) jTableMedia.getRowSorter();
    
        if (sorter == null) return; 
        String filtroSeleccionado = (String) jComboBoxFiltro.getSelectedItem();
    
        if (filtroSeleccionado.equals("All Types")) {
            // CASO A: Mostrar todas las filas.
            sorter.setRowFilter(null); 
        } else {
        // CASO B: Filtrar las filas (el caso que antes estaba en el 'else').
        String mimeTypeFiltro = "";
        // Lógica de traducción
        if (filtroSeleccionado.contains("MP4")) {
            mimeTypeFiltro = "video/mp4";
        } else if (filtroSeleccionado.contains("AVI")) {
            mimeTypeFiltro = "video/x-msvideo";
        } else if (filtroSeleccionado.contains("MP3")) {
            mimeTypeFiltro = "audio/mpeg";
        }
        
        // Aplicar el filtro a la Columna 2 (MIME Type)
        javax.swing.RowFilter<Object, Object> rf = 
            javax.swing.RowFilter.regexFilter("^" + mimeTypeFiltro + "$", 2);
            
        sorter.setRowFilter(rf);
    }
    }//GEN-LAST:event_jComboBoxFiltroActionPerformed

    private void initFiltroComboBox() {
        // 1. Definimos las opciones de filtro con nombres amigables para el usuario
        String[] tiposDeFiltro = {
            "All Types",      // Opción 0: Desactivar filtro
            "Video (MP4)",    // Opción para buscar "video/mp4"
            "Audio (MP3)",    // Opción para buscar "audio/mpeg"
            "Video (AVI)"     // Opción para buscar "video/x-msvideo"
        };

        // 2. Asignamos las opciones al JComboBox
        javax.swing.DefaultComboBoxModel<String> modeloFiltro = new javax.swing.DefaultComboBoxModel<>(tiposDeFiltro);
        jComboBoxFiltro.setModel(modeloFiltro); 
    
        // 3. Conectamos el JComboBox a la lógica de acción
        jComboBoxFiltro.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            // Llama al método que contiene la lógica del RowFilter
            jComboBoxFiltroActionPerformed(evt);
        }
    });
}
    
    private void initBusqueda() {
        jTextFieldBusqueda.getDocument().addDocumentListener(new DocumentListener(){
           
            private void handleUpdate(){
                String texto = jTextFieldBusqueda.getText();
                actualizarBusqueda(texto);
            }
            
            @Override
            public void insertUpdate(DocumentEvent e){
                handleUpdate();
            }
            
            @Override
            public void removeUpdate(DocumentEvent e){
                handleUpdate();
            }
            
            @Override
            public void changedUpdate(DocumentEvent e){
            }
        });
    }
    
    private void initJlist(){
        
        //Creamos el modelo que almacena los objetos de InformacionDescargas
        DefaultListModel<InformacionDescargas> modeloLista = new DefaultListModel<>();
        
        //Leemos cada elemento de la lista y lo añadimos
        for (InformacionDescargas recurso : listaRecursos){
            modeloLista.addElement(recurso);
        }
        
        @SuppressWarnings("unchecked")
        javax.swing.ListModel modeloRaw = (javax.swing.ListModel) modeloLista;
        jListTextFilter.setModel(modeloRaw);
    }
    
    private void actualizarBusqueda(String textoBusqueda){
        
        @SuppressWarnings("unchecked")
        javax.swing.table.TableRowSorter<InformacionDescargasTableModel> sorter = 
        (javax.swing.table.TableRowSorter<InformacionDescargasTableModel>) jTableMedia.getRowSorter();
        
        if (sorter == null) return;
        
        if (textoBusqueda.isEmpty()){
            sorter.setRowFilter(null);
        } else {
            String regex = "(?i)" + java.util.regex.Pattern.quote(textoBusqueda);
            
            javax.swing.RowFilter<Object, Object> rf = javax.swing.RowFilter.regexFilter(regex, 0);
            sorter.setRowFilter(rf);
        }
        
        DefaultListModel<InformacionDescargas> modeloListaFiltrada = new DefaultListModel<>();
        int filasVisibles = sorter.getViewRowCount();
        for (int i = 0; i < filasVisibles; i++){
            int indiceModeloOriginal = sorter.convertRowIndexToModel(i);
            
            InformacionDescargas recurso = listaRecursos.get(indiceModeloOriginal);
            
            modeloListaFiltrada.addElement(recurso);
        }
        @SuppressWarnings("unchecked")
        javax.swing.ListModel modeloRawFiltrado = (javax.swing.ListModel) modeloListaFiltrada;
        jListTextFilter.setModel(modeloRawFiltrado);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxFiltro;
    private javax.swing.JLabel jLabelFiltro;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JList<String> jListTextFilter;
    private javax.swing.JScrollPane jScrollPaneMedia;
    private javax.swing.JScrollPane jScrollPaneTextFilter;
    private javax.swing.JTable jTableMedia;
    private javax.swing.JTextField jTextFieldBusqueda;
    // End of variables declaration//GEN-END:variables
}
