
import java.io.File;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author LionKeriot
 */
public class PanelPreferencias extends javax.swing.JPanel {
    
    private JFrame pantallaPrincipal;
    private JPanel panelOriginal;
    private String rutaDestino = "";
    private String rutaBinarios;
    /**
    * Crea el panel de preferencias.
    * @param pantallaPrincipal la ventana principal que contiene este panel
    */

    public PanelPreferencias(JFrame pantallaPrincipal, JPanel panelOriginal) {
        initComponents();
        this.pantallaPrincipal = pantallaPrincipal;
        this.panelOriginal = panelOriginal;
        
        Preferences prefs = Preferences.userRoot().node(this.getClass().getName());
        this.rutaBinarios = prefs.get("rutaBinarios", "C:\\Users\\ruben\\AppData\\Local\\yt-dlp.exe");
        jLabelBinaries.setText("Binaries path: " + rutaBinarios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTemporales = new javax.swing.JPanel();
        jLabelTemporales = new javax.swing.JLabel();
        jButtonTemporales = new javax.swing.JButton();
        jPanelPlaylists = new javax.swing.JPanel();
        jLabelPlaylists = new javax.swing.JLabel();
        jCheckBoxPlaylists = new javax.swing.JCheckBox();
        jPanelLimite = new javax.swing.JPanel();
        jLabelLimite = new javax.swing.JLabel();
        jComboBoxLimite = new javax.swing.JComboBox<>();
        jPanelBinaries = new javax.swing.JPanel();
        jLabelBinaries = new javax.swing.JLabel();
        jButtonBinaries = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        jPanelTemporales.setLayout(null);

        jLabelTemporales.setText("Temporary files path:");
        jPanelTemporales.add(jLabelTemporales);
        jLabelTemporales.setBounds(0, 0, 320, 20);

        jButtonTemporales.setText("Choose");
        jButtonTemporales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTemporalesActionPerformed(evt);
            }
        });
        jPanelTemporales.add(jButtonTemporales);
        jButtonTemporales.setBounds(430, 0, 75, 23);

        add(jPanelTemporales);
        jPanelTemporales.setBounds(10, 20, 650, 30);

        jPanelPlaylists.setLayout(null);

        jLabelPlaylists.setText("Create m3u file for Playlists:");
        jPanelPlaylists.add(jLabelPlaylists);
        jLabelPlaylists.setBounds(0, 0, 146, 20);

        jCheckBoxPlaylists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPlaylistsActionPerformed(evt);
            }
        });
        jPanelPlaylists.add(jCheckBoxPlaylists);
        jCheckBoxPlaylists.setBounds(430, 0, 20, 20);

        add(jPanelPlaylists);
        jPanelPlaylists.setBounds(10, 60, 580, 20);

        jPanelLimite.setLayout(null);

        jLabelLimite.setText("Limit download speed:");
        jPanelLimite.add(jLabelLimite);
        jLabelLimite.setBounds(0, 0, 130, 20);

        jComboBoxLimite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unlimited", "100 MB/s", "10 MB/s", "1 MB/s", " " }));
        jComboBoxLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLimiteActionPerformed(evt);
            }
        });
        jPanelLimite.add(jComboBoxLimite);
        jComboBoxLimite.setBounds(430, 0, 100, 22);

        add(jPanelLimite);
        jPanelLimite.setBounds(10, 100, 640, 30);

        jPanelBinaries.setLayout(null);

        jLabelBinaries.setText("Binaries path:");
        jPanelBinaries.add(jLabelBinaries);
        jLabelBinaries.setBounds(0, 0, 380, 20);

        jButtonBinaries.setText("Change Binaries Path");
        jButtonBinaries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBinariesActionPerformed(evt);
            }
        });
        jPanelBinaries.add(jButtonBinaries);
        jButtonBinaries.setBounds(430, 0, 150, 20);

        add(jPanelBinaries);
        jPanelBinaries.setBounds(10, 140, 830, 30);

        jButtonVolver.setText("Go back");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        add(jButtonVolver);
        jButtonVolver.setBounds(10, 180, 73, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTemporalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTemporalesActionPerformed
    JFileChooser chooser = new JFileChooser();
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

    int result = chooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFolder = chooser.getSelectedFile();
        String rutaTemporal = selectedFolder.getAbsolutePath();

    // Guarda la ruta donde quieras (por ejemplo, en una variable global o en un campo de texto)
    jLabelTemporales.setText(rutaTemporal); // ejemplo visual
    this.rutaDestino = rutaTemporal;     // ejemplo funcional
}

    
    }//GEN-LAST:event_jButtonTemporalesActionPerformed

    private void jCheckBoxPlaylistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPlaylistsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPlaylistsActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        
        pantallaPrincipal.setContentPane(panelOriginal);
        pantallaPrincipal.revalidate();
        pantallaPrincipal.repaint();

    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonBinariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBinariesActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = chooser.getSelectedFile();
        rutaBinarios = selectedFile.getAbsolutePath();

        jLabelBinaries.setText("Binaries path: " + rutaBinarios);
        Preferences prefs = Preferences.userRoot().node(this.getClass().getName());
        prefs.put("rutaBinarios", rutaBinarios);
        }
    }//GEN-LAST:event_jButtonBinariesActionPerformed

    private void jComboBoxLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLimiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLimiteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBinaries;
    private javax.swing.JButton jButtonTemporales;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JCheckBox jCheckBoxPlaylists;
    private javax.swing.JComboBox<String> jComboBoxLimite;
    private javax.swing.JLabel jLabelBinaries;
    private javax.swing.JLabel jLabelLimite;
    private javax.swing.JLabel jLabelPlaylists;
    private javax.swing.JLabel jLabelTemporales;
    private javax.swing.JPanel jPanelBinaries;
    private javax.swing.JPanel jPanelLimite;
    private javax.swing.JPanel jPanelPlaylists;
    private javax.swing.JPanel jPanelTemporales;
    // End of variables declaration//GEN-END:variables
}
