/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author LionKeriot
 */
public class PanelPreferencias extends javax.swing.JPanel {

    /**
     * Creates new form PanelPreferencias
     */
    public PanelPreferencias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTemporales = new javax.swing.JPanel();
        jLabelTemporales = new javax.swing.JLabel();
        jButtonTemporales = new javax.swing.JButton();
        jPanelPlaylists = new javax.swing.JPanel();
        jLabelPlaylists = new javax.swing.JLabel();
        jCheckBoxPlaylists = new javax.swing.JCheckBox();
        jPanelLimite = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanelBinaries = new javax.swing.JPanel();
        jLabelBinaries = new javax.swing.JLabel();
        jTextFieldBinaries = new javax.swing.JTextField();
        jButtonBinaries = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        jPanelTemporales.setLayout(null);

        jLabelTemporales.setText("Temporary files path:");
        jPanelTemporales.add(jLabelTemporales);
        jLabelTemporales.setBounds(0, 0, 112, 20);

        jButtonTemporales.setText("Choose");
        jButtonTemporales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTemporalesActionPerformed(evt);
            }
        });
        jPanelTemporales.add(jButtonTemporales);
        jButtonTemporales.setBounds(170, 0, 75, 23);

        add(jPanelTemporales);
        jPanelTemporales.setBounds(10, 20, 270, 30);

        jPanelPlaylists.setLayout(null);

        jLabelPlaylists.setText("Create m3u file for Playlists:");
        jPanelPlaylists.add(jLabelPlaylists);
        jLabelPlaylists.setBounds(0, 0, 146, 20);

        jCheckBoxPlaylists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPlaylistsActionPerformed(evt);
            }
        });
        jPanelPlaylists.add(jCheckBoxPlaylists);
        jCheckBoxPlaylists.setBounds(170, 0, 20, 20);

        add(jPanelPlaylists);
        jPanelPlaylists.setBounds(10, 60, 270, 20);

        jPanelLimite.setLayout(null);

        jLabel1.setText("Limit download speed:");
        jPanelLimite.add(jLabel1);
        jLabel1.setBounds(0, 0, 130, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 MB/s", "10 MB/s", "100 MB/s", "Unlimited" }));
        jPanelLimite.add(jComboBox1);
        jComboBox1.setBounds(170, 0, 100, 22);

        add(jPanelLimite);
        jPanelLimite.setBounds(10, 100, 290, 30);

        jPanelBinaries.setLayout(null);

        jLabelBinaries.setText("Binaries path:");
        jPanelBinaries.add(jLabelBinaries);
        jLabelBinaries.setBounds(0, 0, 80, 20);
        jPanelBinaries.add(jTextFieldBinaries);
        jTextFieldBinaries.setBounds(170, 0, 300, 20);

        jButtonBinaries.setText("Change it!");
        jPanelBinaries.add(jButtonBinaries);
        jButtonBinaries.setBounds(480, 0, 90, 20);

        add(jPanelBinaries);
        jPanelBinaries.setBounds(10, 140, 670, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTemporalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTemporalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTemporalesActionPerformed

    private void jCheckBoxPlaylistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPlaylistsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPlaylistsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBinaries;
    private javax.swing.JButton jButtonTemporales;
    private javax.swing.JCheckBox jCheckBoxPlaylists;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBinaries;
    private javax.swing.JLabel jLabelPlaylists;
    private javax.swing.JLabel jLabelTemporales;
    private javax.swing.JPanel jPanelBinaries;
    private javax.swing.JPanel jPanelLimite;
    private javax.swing.JPanel jPanelPlaylists;
    private javax.swing.JPanel jPanelTemporales;
    private javax.swing.JTextField jTextFieldBinaries;
    // End of variables declaration//GEN-END:variables
}
