
import java.util.List;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Date;
import java.util.prefs.Preferences;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LionKeriot
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());
    private String rutaDestino = "";
    private JPanel panelOriginal;
    private String rutaBinarios = "";
    private PanelPreferencias panelPreferencias;
    private List<InformacionDescargas> listaRecursos = new ArrayList<>();
  

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
    initComponents();
    this.setLocationRelativeTo(null);
    
    panelOriginal = (JPanel) getContentPane();
    jButtonCambiar.setVisible(false); // Ocultar botón de cambiar al inicio
    jLabelGuardar.setText("No folder selected"); // Texto inicial
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCalidad = new javax.swing.ButtonGroup();
        jLabelWelcome = new javax.swing.JLabel();
        jPanelWeb = new javax.swing.JPanel();
        jLabelUrl = new javax.swing.JLabel();
        jTextFieldUrl = new javax.swing.JTextField();
        jPanelCalidad = new javax.swing.JPanel();
        jLabelCalidad = new javax.swing.JLabel();
        jRadioButton1080 = new javax.swing.JRadioButton();
        jRadioButton720 = new javax.swing.JRadioButton();
        jRadioButton480 = new javax.swing.JRadioButton();
        jPanelSubtitulos = new javax.swing.JPanel();
        jLabelSubtitulos = new javax.swing.JLabel();
        jCheckBoxSubtitulosSi = new javax.swing.JCheckBox();
        jPanelFormato = new javax.swing.JPanel();
        jLabelFormato = new javax.swing.JLabel();
        jComboBoxFormato = new javax.swing.JComboBox<>();
        jPanelGuardado = new javax.swing.JPanel();
        jLabelGuardar = new javax.swing.JLabel();
        jButtonRutaGuardado = new javax.swing.JButton();
        jButtonCambiar = new javax.swing.JButton();
        jPanelProgreso = new javax.swing.JPanel();
        jLabelProgreso = new javax.swing.JLabel();
        jProgressBarra = new javax.swing.JProgressBar();
        jPanelConsola = new javax.swing.JPanel();
        jScrollPaneConsola = new javax.swing.JScrollPane();
        jTextAreaConsola = new javax.swing.JTextArea();
        jPanelDescarga = new javax.swing.JPanel();
        jButtonDescarga = new javax.swing.JButton();
        jPanelLibrary = new javax.swing.JPanel();
        jButtonLibrary = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemPreferences = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YourDownload");
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(null);

        jLabelWelcome.setText("Welcome! Download videos with no barriers!");
        getContentPane().add(jLabelWelcome);
        jLabelWelcome.setBounds(10, 10, 240, 16);

        jPanelWeb.setLayout(null);

        jLabelUrl.setText("URL site:");
        jPanelWeb.add(jLabelUrl);
        jLabelUrl.setBounds(0, 0, 50, 20);

        jTextFieldUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUrlActionPerformed(evt);
            }
        });
        jPanelWeb.add(jTextFieldUrl);
        jTextFieldUrl.setBounds(110, 0, 670, 30);

        getContentPane().add(jPanelWeb);
        jPanelWeb.setBounds(10, 50, 780, 30);

        jPanelCalidad.setLayout(null);

        jLabelCalidad.setText("Output Resolution:");
        jPanelCalidad.add(jLabelCalidad);
        jLabelCalidad.setBounds(0, 0, 100, 16);

        buttonGroupCalidad.add(jRadioButton1080);
        jRadioButton1080.setText("1080p");
        jRadioButton1080.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1080ActionPerformed(evt);
            }
        });
        jPanelCalidad.add(jRadioButton1080);
        jRadioButton1080.setBounds(110, 0, 60, 21);

        buttonGroupCalidad.add(jRadioButton720);
        jRadioButton720.setText("720p");
        jPanelCalidad.add(jRadioButton720);
        jRadioButton720.setBounds(170, 0, 50, 21);

        buttonGroupCalidad.add(jRadioButton480);
        jRadioButton480.setText("480p");
        jPanelCalidad.add(jRadioButton480);
        jRadioButton480.setBounds(220, 0, 50, 21);

        getContentPane().add(jPanelCalidad);
        jPanelCalidad.setBounds(10, 90, 270, 20);

        jPanelSubtitulos.setLayout(null);

        jLabelSubtitulos.setText("Download Subtitles:");
        jPanelSubtitulos.add(jLabelSubtitulos);
        jLabelSubtitulos.setBounds(0, 0, 110, 20);

        jCheckBoxSubtitulosSi.setText("Yes");
        jCheckBoxSubtitulosSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSubtitulosSiActionPerformed(evt);
            }
        });
        jPanelSubtitulos.add(jCheckBoxSubtitulosSi);
        jCheckBoxSubtitulosSi.setBounds(120, 0, 84, 20);

        getContentPane().add(jPanelSubtitulos);
        jPanelSubtitulos.setBounds(320, 90, 170, 30);

        jPanelFormato.setLayout(null);

        jLabelFormato.setText("Output Format:");
        jPanelFormato.add(jLabelFormato);
        jLabelFormato.setBounds(0, 0, 90, 20);

        jComboBoxFormato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".mp4", ".avi", ".mp3" }));
        jComboBoxFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFormatoActionPerformed(evt);
            }
        });
        jPanelFormato.add(jComboBoxFormato);
        jComboBoxFormato.setBounds(110, 0, 72, 22);

        getContentPane().add(jPanelFormato);
        jPanelFormato.setBounds(10, 130, 190, 30);

        jPanelGuardado.setLayout(null);

        jLabelGuardar.setText("Destination folder:");
        jPanelGuardado.add(jLabelGuardar);
        jLabelGuardar.setBounds(0, 0, 260, 20);

        jButtonRutaGuardado.setText("Choose save location");
        jButtonRutaGuardado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRutaGuardadoActionPerformed(evt);
            }
        });
        jPanelGuardado.add(jButtonRutaGuardado);
        jButtonRutaGuardado.setBounds(110, 0, 150, 20);

        jButtonCambiar.setText("Change");
        jButtonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarActionPerformed(evt);
            }
        });
        jPanelGuardado.add(jButtonCambiar);
        jButtonCambiar.setBounds(270, 0, 72, 20);

        getContentPane().add(jPanelGuardado);
        jPanelGuardado.setBounds(10, 170, 440, 20);

        jPanelProgreso.setLayout(null);

        jLabelProgreso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelProgreso.setText("Completed:");
        jPanelProgreso.add(jLabelProgreso);
        jLabelProgreso.setBounds(0, -10, 100, 40);
        jPanelProgreso.add(jProgressBarra);
        jProgressBarra.setBounds(110, 0, 670, 20);

        getContentPane().add(jPanelProgreso);
        jPanelProgreso.setBounds(10, 210, 780, 30);

        jPanelConsola.setLayout(null);

        jTextAreaConsola.setColumns(20);
        jTextAreaConsola.setRows(5);
        jScrollPaneConsola.setViewportView(jTextAreaConsola);

        jPanelConsola.add(jScrollPaneConsola);
        jScrollPaneConsola.setBounds(0, 0, 990, 470);

        getContentPane().add(jPanelConsola);
        jPanelConsola.setBounds(10, 250, 990, 470);

        jPanelDescarga.setLayout(null);

        jButtonDescarga.setText("Download!");
        jButtonDescarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDescargaActionPerformed(evt);
            }
        });
        jPanelDescarga.add(jButtonDescarga);
        jButtonDescarga.setBounds(0, 0, 170, 60);

        getContentPane().add(jPanelDescarga);
        jPanelDescarga.setBounds(830, 40, 170, 60);

        jPanelLibrary.setLayout(null);

        jButtonLibrary.setText("Media Library");
        jButtonLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLibraryActionPerformed(evt);
            }
        });
        jPanelLibrary.add(jButtonLibrary);
        jButtonLibrary.setBounds(0, 0, 170, 60);

        getContentPane().add(jPanelLibrary);
        jPanelLibrary.setBounds(830, 110, 170, 60);

        jMenuFile.setText("File");

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar.add(jMenuFile);

        jMenuEdit.setText("Edit");

        jMenuItemPreferences.setText("Preferences");
        jMenuItemPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPreferencesActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemPreferences);

        jMenuBar.add(jMenuEdit);

        jMenuHelp.setText("Help");

        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar.add(jMenuHelp);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUrlActionPerformed

    private void jRadioButton1080ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1080ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1080ActionPerformed

    private void jCheckBoxSubtitulosSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSubtitulosSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSubtitulosSiActionPerformed

    private void jButtonRutaGuardadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRutaGuardadoActionPerformed
        // Filechooser para seleccionar una ruta
        JFileChooser selectorRuta = new JFileChooser();
        selectorRuta.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int resultado = selectorRuta.showOpenDialog(this); // selecciona la ruta 
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File carpeta = selectorRuta.getSelectedFile();
            rutaDestino = carpeta.getAbsolutePath();

            jLabelGuardar.setText("Saved at: " + rutaDestino);

            jButtonRutaGuardado.setVisible(false); 
            jButtonCambiar.setVisible(true);  
        }
    }//GEN-LAST:event_jButtonRutaGuardadoActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        String[] opciones = {"Yes", "No"};
        int resultado = JOptionPane.showOptionDialog(this, "Are you sure you want to exit?",
                "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, 
                opciones, opciones[0]);
        
            if (resultado == 0) {
            System.exit(0);
            } 
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        About dialog = new About(this, true); // 'this' es tu JFrame principal
        dialog.setLocationRelativeTo(this); // Centrado respecto a la ventana principal
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItemPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPreferencesActionPerformed
    setContentPane(new PanelPreferencias(this, panelOriginal));
    revalidate();
    repaint();
    }//GEN-LAST:event_jMenuItemPreferencesActionPerformed

    private void jButtonDescargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDescargaActionPerformed
        final String url = jTextFieldUrl.getText().trim(); // Le indicamos que coja el texto del TextField
        
        if (url.isEmpty()){
            JOptionPane.showMessageDialog(this, "Introduce una URL válida"); //En caso de que no se introduzca una URL correcta.
            return;
        }
        
        jButtonDescarga.setEnabled(false);
        jTextAreaConsola.setText("");
        jProgressBarra.setValue(0);
        
        // Asignar calidad al video. Simple IF para escoger la calidad. 
        String formatoSeleccionado = "bestvideo+bestaudio"; // Default: la mejor calidad disponible

            if (jRadioButton1080.isSelected()) {
                // Busca el mejor video de 1080p o menos, más el mejor audio
                formatoSeleccionado = "bestvideo[height<=1080]+bestaudio";
            } else if (jRadioButton720.isSelected()) {
                // Busca el mejor video de 720p o menos, más el mejor audio
                formatoSeleccionado = "bestvideo[height<=720]+bestaudio";
            } else if (jRadioButton480.isSelected()) {
                // Busca el mejor video de 480p o menos, más el mejor audio
                formatoSeleccionado = "bestvideo[height<=480]+bestaudio";
            }

            // El resto del código que usa 'formatoFinal' permanece igual
            boolean descargarSubtitulos = jCheckBoxSubtitulosSi.isSelected();
            final String formatoFinal = formatoSeleccionado; // Igualamos a formatoSeleccionado ya que el uso de Thread no permite el cambio de la variable que debe ser final.
        
        new Thread(() -> {
            
            final File[] archivoDescargado = new File [1];
            try {
                
                // construccion comando
                Preferences prefs = Preferences.userRoot().node("PanelPreferencias");
                String rutaBinarios = prefs.get("rutaBinarios", "C:\\Users\\ruben\\AppData\\Local\\yt-dlp.exe");
                List<String> comando = new ArrayList<>();
                comando.add(rutaBinarios);
                comando.add("--no-download-archive");
                comando.add("--restrict-filenames");
                String formatoSalida = jComboBoxFormato.getSelectedItem().toString();

                if (formatoSalida.contains(".mp3")) {
                    // no se especifica -f para audio
                    comando.add("-x");
                    comando.add("--audio-format");
                    comando.add("mp3");
                } else {
                    // se especifica -f 
                    comando.add("-f");
                    comando.add(formatoFinal);

                    if (formatoSalida.contains(".mp4")) {
                        comando.add("--recode-video");
                        comando.add("mp4");
                    } else if (formatoSalida.contains(".avi")) {
                        comando.add("--recode-video");
                        comando.add("avi");
                    }
                }
                if (!rutaDestino.isEmpty()) {
                    comando.add("-o");
                    comando.add(rutaDestino + File.separator + "%(title)s - %(epoch)s.%(ext)s");
                }

                if (!rutaDestino.isEmpty()) {
                comando.add("--paths");
                comando.add("temp:" + rutaDestino);
                }       

                comando.add(url);

                if (descargarSubtitulos) {
                    comando.add("--write-auto-sub");       // descarga subtítulos
                    comando.add("--sub-lang");
                    comando.add("en");                // idioma español
                    comando.add("--convert-subs");
                    comando.add("srt");               // formato .srt
                }
                
                System.out.println("Comando final: " + String.join(" ", comando));
                ProcessBuilder builder = new ProcessBuilder(comando); // Añadimos -f para que seleccione formato.
                builder.redirectErrorStream(true);
                Process process = builder.start();
                
                
                BufferedReader reader = new BufferedReader (new InputStreamReader(process.getInputStream()));
                String line;
                while ((line = reader.readLine()) != null) {
                    final String outputLine = line;
                    if (outputLine.contains("Destination:")) {
                        String ruta = outputLine.substring(outputLine.indexOf("Destination:") + 12).trim();
                        archivoDescargado[0] = new File(ruta);
                        System.out.println("Archivo detectado (Destination): " + ruta);
                    } else if (outputLine.contains("Merging formats into")) {
                        String ruta = outputLine.substring(outputLine.indexOf("Merging formats into") + 22).trim().replaceAll("\"", "");
                        archivoDescargado[0] = new File(ruta);
                        System.out.println("Archivo detectado (Merge): " + ruta);
                    } else if (outputLine.contains("Deleting original file") && archivoDescargado[0] == null) {
                        // En caso de que se haya convertido y el original se haya eliminado
                        int start = outputLine.indexOf("Deleting original file") + 25;
                        int end = outputLine.lastIndexOf("\"");
                        if (start < end) {
                            String ruta = outputLine.substring(start, end).trim().replaceAll("\"", "");
                            archivoDescargado[0] = new File(ruta);
                            System.out.println("Archivo detectado (Deleted original): " + ruta);
                        }
                    }   

                    
                    SwingUtilities.invokeLater(() -> {
                        jTextAreaConsola.append (outputLine + "\n");
                        jTextAreaConsola.setCaretPosition(jTextAreaConsola.getDocument().getLength());
                        actualizarBarraProgreso(outputLine);
                    });
                }
                    process.waitFor();
            } catch (IOException | InterruptedException e){
                SwingUtilities.invokeLater(() -> jTextAreaConsola.append("Error: " + e.getMessage() + "\n"));
            } finally {
                SwingUtilities.invokeLater(() -> {
                jButtonDescarga.setEnabled(true);
                
                //Recogemos las propiedades del archivo descargado
                File archivoFinal = archivoDescargado[0];
                System.out.println("DEBUG (Descarga): Ruta de archivo final: " + archivoFinal.getAbsolutePath());
                System.out.println("DEBUG (Descarga): ¿Existe el archivo?: " + archivoFinal.exists());
                if (archivoFinal != null && archivoFinal.exists()){
                    String rutaAbsoluta = archivoFinal.getAbsolutePath();
                    long tamanyo = archivoFinal.length();
                    String mimeType = obtenerMimeSimple(archivoFinal.getName());
                // Y lo añadimos a la listaRecursos
                    InformacionDescargas nuevaDescarga = new InformacionDescargas(rutaAbsoluta, new Date(), tamanyo, mimeType);
                    listaRecursos.add(nuevaDescarga);
                }

                // Muestra el Jdialog de descarga completada
                DescargaCompletada dialog = new DescargaCompletada(null, true, archivoDescargado[0]);
                dialog.setSize(300, 250);               
                dialog.setLocationRelativeTo(null);     
                dialog.setVisible(true);                
            });
        }
        }).start();
    }//GEN-LAST:event_jButtonDescargaActionPerformed

    private void jComboBoxFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFormatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFormatoActionPerformed

    private void jButtonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarActionPerformed
    JFileChooser selectorRuta = new JFileChooser();
    selectorRuta.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

    int resultado = selectorRuta.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File carpeta = selectorRuta.getSelectedFile();
            rutaDestino = carpeta.getAbsolutePath();

            jLabelGuardar.setText("Saved at: " + rutaDestino);
            // No necesitas cambiar visibilidad aquí
        }
    }//GEN-LAST:event_jButtonCambiarActionPerformed

    private void jButtonLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLibraryActionPerformed
        MediaLibrary panelBiblioteca = new MediaLibrary(this, panelOriginal, listaRecursos);
        
        setContentPane(panelBiblioteca);
        revalidate();
        repaint();
        System.out.println("DEBUG: Se abre MediaLibrary. Contiene " + listaRecursos.size() + " archivos.");
    }//GEN-LAST:event_jButtonLibraryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }
    
    private void actualizarBarraProgreso(String line) {
    Pattern pattern = Pattern.compile("\\[download\\]\\s+(\\d+\\.\\d+)%");
    Matcher matcher = pattern.matcher(line);
        if (matcher.find()) {
            double porcentaje = Double.parseDouble(matcher.group(1));
            jProgressBarra.setValue((int) porcentaje);
        }
    }
    
    
    /**
    * Determina un tipo MIME (formato de contenido) simple basado en la extensión del archivo.
    * * Esta función es auxiliar para categorizar el archivo descargado 
     * (MP4, AVI, MP3) para la biblioteca.
    *
     * @param nombreArchivo El nombre completo del archivo (e.g., "MiVideo.mp4").
    * @return El String que representa el tipo MIME estándar (e.g., "video/mp4").
     */
    private String obtenerMimeSimple(String nombreArchivo){
        if (nombreArchivo.toLowerCase().endsWith(".mp4")) {
            return "video/mp4";
        } else if (nombreArchivo.toLowerCase().endsWith (".avi")) {
            return "video/x-msvideo";
        } else if (nombreArchivo.toLowerCase().endsWith (".mp3")) {
            return "audio/mpeg";
        }
        return "application/octet-stream";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCalidad;
    private javax.swing.JButton jButtonCambiar;
    private javax.swing.JButton jButtonDescarga;
    private javax.swing.JButton jButtonLibrary;
    private javax.swing.JButton jButtonRutaGuardado;
    private javax.swing.JCheckBox jCheckBoxSubtitulosSi;
    private javax.swing.JComboBox<String> jComboBoxFormato;
    private javax.swing.JLabel jLabelCalidad;
    private javax.swing.JLabel jLabelFormato;
    private javax.swing.JLabel jLabelGuardar;
    private javax.swing.JLabel jLabelProgreso;
    private javax.swing.JLabel jLabelSubtitulos;
    private javax.swing.JLabel jLabelUrl;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemPreferences;
    private javax.swing.JPanel jPanelCalidad;
    private javax.swing.JPanel jPanelConsola;
    private javax.swing.JPanel jPanelDescarga;
    private javax.swing.JPanel jPanelFormato;
    private javax.swing.JPanel jPanelGuardado;
    private javax.swing.JPanel jPanelLibrary;
    private javax.swing.JPanel jPanelProgreso;
    private javax.swing.JPanel jPanelSubtitulos;
    private javax.swing.JPanel jPanelWeb;
    private javax.swing.JProgressBar jProgressBarra;
    private javax.swing.JRadioButton jRadioButton1080;
    private javax.swing.JRadioButton jRadioButton480;
    private javax.swing.JRadioButton jRadioButton720;
    private javax.swing.JScrollPane jScrollPaneConsola;
    private javax.swing.JTextArea jTextAreaConsola;
    private javax.swing.JTextField jTextFieldUrl;
    // End of variables declaration//GEN-END:variables
}

