
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_OPTION;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author LionKeriot
 */
public class SearchDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchDialog.class.getName());
    private final List<InformacionDescargas> listaRecursos;
    /**
     * Creates new form SearchDialog
     */
    public SearchDialog(java.awt.Frame parent, List<InformacionDescargas> listaRecursos) {
        super(parent, true);
        this.listaRecursos = listaRecursos;
        initComponents();
 
        javax.swing.SwingUtilities.invokeLater(() -> {
        // Estas líneas ahora se ejecutarán después de que la ventana esté lista.
        initBusqueda();
        aplicarFiltroBusqueda(""); 
    });
        
        setTitle("Search Files");
        setSize(1024,768);
        setLocationRelativeTo(parent);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldIntroducir = new javax.swing.JTextField();
        jScrollPaneList = new javax.swing.JScrollPane();
        jListSearchList = new javax.swing.JList<>();
        jButtonPlay = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextFieldIntroducir.setText("Enter a word");
        jTextFieldIntroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntroducirActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIntroducir);
        jTextFieldIntroducir.setBounds(30, 16, 279, 30);

        jListSearchList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneList.setViewportView(jListSearchList);

        getContentPane().add(jScrollPaneList);
        jScrollPaneList.setBounds(30, 81, 888, 100);

        jButtonPlay.setText("Play it!");
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlay);
        jButtonPlay.setBounds(30, 250, 72, 23);

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete);
        jButtonDelete.setBounds(120, 250, 72, 23);

        jButtonReturn.setText("Return");
        jButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReturn);
        jButtonReturn.setBounds(210, 250, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
      Object selectedValue = jListSearchList.getSelectedValue();
      InformacionDescargas recurso = (InformacionDescargas) selectedValue;
        
        if (recurso != null){
            java.io.File archivo = new java.io.File(recurso.getRutaAbsoluta());
            
            if (archivo.exists()){
                try {
                    java.awt.Desktop.getDesktop().open(archivo);
                } catch (java.io.IOException e){
                    JOptionPane.showMessageDialog(this, "Error opening the file: " + e.getMessage(), "I/O error", JOptionPane.ERROR_MESSAGE);
                    logger.log(java.util.logging.Level.SEVERE, "Error opening the file.", e);
                }
            } else {
                JOptionPane.showMessageDialog(this, "File not found","Error", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "First, select a valid file.");
        }
        
    }//GEN-LAST:event_jButtonPlayActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
    
    Object selectedValue = jListSearchList.getSelectedValue();
    InformacionDescargas recursoAEliminar = (InformacionDescargas) selectedValue;

        if (recursoAEliminar == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un archivo primero.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
    
    Object[] opciones = {"Yes", "No"};
    int resultadoConfirmacion = javax.swing.JOptionPane.showOptionDialog(this,
        "Are you sure you want to delete '" + recursoAEliminar.getNombreArchivo() + "'?\nThis action will delete the file from the disk.",
        "Confirm Deletion",
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.QUESTION_MESSAGE,
        null, opciones, opciones[0]
    );

    if (resultadoConfirmacion == YES_OPTION) {
        java.io.File archivo = new java.io.File(recursoAEliminar.getRutaAbsoluta());
            if (archivo.delete()) {
                listaRecursos.remove(recursoAEliminar);
                aplicarFiltroBusqueda(jTextFieldIntroducir.getText());
                javax.swing.JOptionPane.showMessageDialog(this, "File deleted successfully.", "Success!", javax.swing.JOptionPane.INFORMATION_MESSAGE); 
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error: File could not be deleted. Check if the file is currently open.", 
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTextFieldIntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntroducirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntroducirActionPerformed

    private void jButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonReturnActionPerformed
    
    private void initBusqueda() {
        jTextFieldIntroducir.getDocument().addDocumentListener(new DocumentListener(){
           
            private void handleUpdate(){
                String texto = jTextFieldIntroducir.getText();
                aplicarFiltroBusqueda(texto);
            }
            
            @Override
            public void insertUpdate(DocumentEvent e){
                handleUpdate();
            }
            
            @Override
            public void removeUpdate(DocumentEvent e){
                handleUpdate();
            }
            
            @Override
            public void changedUpdate(DocumentEvent e){
            }
        });
    }
    
    private void aplicarFiltroBusqueda(String textoBusqueda) {
    
        String textoBusquedaLower = textoBusqueda.toLowerCase();
        DefaultListModel<InformacionDescargas> modeloResultados = new DefaultListModel<>();

        if (textoBusqueda.isEmpty()) {
            for (InformacionDescargas recurso : listaRecursos) {
                modeloResultados.addElement(recurso);
            }
        } else {
            for (InformacionDescargas recurso : listaRecursos) {

                String nombreArchivoLower = recurso.getNombreArchivo().toLowerCase();

                if (nombreArchivoLower.contains(textoBusquedaLower)) {
                    modeloResultados.addElement(recurso);
                }
            }
        }
    @SuppressWarnings("unchecked")
        javax.swing.ListModel modeloRaw = (javax.swing.ListModel) modeloResultados;
        jListSearchList.setModel(modeloRaw);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JButton jButtonReturn;
    private javax.swing.JList<String> jListSearchList;
    private javax.swing.JScrollPane jScrollPaneList;
    private javax.swing.JTextField jTextFieldIntroducir;
    // End of variables declaration//GEN-END:variables
}
