package com.gomez.yourdownload.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author LionKeriot
 */
public class About extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(About.class.getName());

    /**
     * Creates new form About
     */
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(350, 250);
        setLocationRelativeTo(null); // Centra en pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jLabelCourse = new javax.swing.JLabel();
        jLabelAbout = new javax.swing.JLabel();
        jLabelFonts = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelName.setText("Full name: Rubén Gómez Hernández");
        getContentPane().add(jLabelName);
        jLabelName.setBounds(10, 60, 290, 16);

        jLabelCourse.setText("Course: 2º Desarrollo de aplicaciones Multiplataforma");
        getContentPane().add(jLabelCourse);
        jLabelCourse.setBounds(10, 80, 290, 16);

        jLabelAbout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelAbout.setText("About...");
        getContentPane().add(jLabelAbout);
        jLabelAbout.setBounds(150, 10, 70, 30);

        jLabelFonts.setText("Sources used: yt-dlp, ffmpeg, ffprobe, copilot, stack overflow");
        getContentPane().add(jLabelFonts);
        jLabelFonts.setBounds(10, 100, 340, 16);

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit);
        jButtonExit.setBounds(140, 150, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        dispose(); // Cierra el diálogo
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabelAbout;
    private javax.swing.JLabel jLabelCourse;
    private javax.swing.JLabel jLabelFonts;
    private javax.swing.JLabel jLabelName;
    // End of variables declaration//GEN-END:variables
}
