package com.gomez.yourdownload.view;
/**
 * Dialog window that displays information about the application, 
 * the developer, and the sources used.
 * @author Rubén Gómez Hernández
 * @version 1.0
 */
public class About extends javax.swing.JDialog {
    /** 
    * Logger instance for event tracking in this dialog. 
    */
    public static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(About.class.getName());

    /**
     * Creates a new instance of the About dialog.
     * @param parent The main application window (Frame).
     * @param modal True if this window should block interaction with the parent window.
     */
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(350, 250);
        setLocationRelativeTo(null); // Centra en pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jLabelCourse = new javax.swing.JLabel();
        jLabelAbout = new javax.swing.JLabel();
        jLabelFonts = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelName.setText("Full name: Rubén Gómez Hernández");
        getContentPane().add(jLabelName);
        jLabelName.setBounds(10, 60, 290, 16);

        jLabelCourse.setText("Course: 2º Desarrollo de aplicaciones Multiplataforma");
        getContentPane().add(jLabelCourse);
        jLabelCourse.setBounds(10, 80, 290, 16);

        jLabelAbout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelAbout.setText("About...");
        getContentPane().add(jLabelAbout);
        jLabelAbout.setBounds(150, 10, 70, 30);

        jLabelFonts.setText("Sources used: yt-dlp, ffmpeg, ffprobe, copilot, stack overflow");
        getContentPane().add(jLabelFonts);
        jLabelFonts.setBounds(10, 100, 340, 16);

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit);
        jButtonExit.setBounds(140, 150, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Closes and disposes of the dialog window.
     * @param evt The action event triggered by the exit button.
     */
    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        dispose(); // close the dialog
    }//GEN-LAST:event_jButtonExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabelAbout;
    private javax.swing.JLabel jLabelCourse;
    private javax.swing.JLabel jLabelFonts;
    private javax.swing.JLabel jLabelName;
    // End of variables declaration//GEN-END:variables
}
