package com.gomez.yourdownload.view;


import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author LionKeriot
 */
public class DownloadComplete extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DownloadComplete.class.getName());
    private File downloadFile;
    /**
     * Creates new form DescargaCompletada
     */
    public DownloadComplete(java.awt.Frame parent, boolean modal, File downloadFile) {
        super(parent, modal);
        initComponents();
        this.downloadFile = downloadFile;
        
        // --- ANULACIÓN PORTABLE DE LA RUTA ABSOLUTA ---
        java.net.URL iconURL = getClass().getResource("/resources/icons/icons8-checkmark-120.png");
    
        // Si se encuentra el recurso en el classpath (dentro del JAR), lo usamos.
        if (iconURL != null) {
        jLabelEnded.setIcon(new javax.swing.ImageIcon(iconURL));
    } else {
        // Opcional: Si el icono no se encuentra, podemos notificarlo.
        System.err.println("Error: Icon resource not found.");
    }
    // ---------------------------------------------
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEnded = new javax.swing.JLabel();
        jButtonPlay = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Download Complete!");
        setModal(true);
        getContentPane().setLayout(null);

        jLabelEnded.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Documents\\NetBeansProjects\\YouDownloadDefinitivo\\resources\\icons\\icons8-checkmark-120.png")); // NOI18N
        jLabelEnded.setText("DOWNLOAD COMPLETED!");
        getContentPane().add(jLabelEnded);
        jLabelEnded.setBounds(0, 20, 290, 120);

        jButtonPlay.setText("Play it!");
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlay);
        jButtonPlay.setBounds(60, 160, 75, 23);

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit);
        jButtonExit.setBounds(150, 160, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        if (downloadFile != null && downloadFile.exists()) {
            try {
            Desktop.getDesktop().open(downloadFile);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Couldn't open file: " + e.getMessage());
        }
        } else {
            JOptionPane.showMessageDialog(this, "File not found.");
        }
    }//GEN-LAST:event_jButtonPlayActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JLabel jLabelEnded;
    // End of variables declaration//GEN-END:variables
}
