package com.gomez.yourdownload.view;

import com.gomez.yourdownload.model.DownloadInfo;
import com.gomez.yourdownload.service.DownloadService;
import com.gomez.yourdownload.view.MediaLibrary;
import java.util.List;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Date;
import java.util.prefs.Preferences;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import com.gomez.component.MediaPoller;

/**
 *
 * @author Rubén Gómez Hernández
 */
public class MainScreen extends javax.swing.JFrame {

    private String destinyPath = "";
    private JPanel originalPanel;
    private List<DownloadInfo> resourcesList;
    private String jwtToken;
    private String currentView = "MAIN";

    public MainScreen(String token, MediaPoller pollerInstance) {
        this.jwtToken = token;// Almacenamos el token JWT para usarlo en descargas, etc.
        this.mediaPoller1 = pollerInstance;

        // 1. Carga de Datos y Creación de UI
        resourcesList = DownloadService.loadHistory();
        initComponents();
        originalPanel = (JPanel) getContentPane();

        jPanelAudioQuality.setVisible(false);
        jPanelQuality.setVisible(true);
        jRadioButton480.setSelected(true);
        jRadioButtonHQ.setSelected(true);
        jPanelConsole.setVisible(false);

        String userHome = System.getProperty("user.home");
        File downloadsFolder = new File(userHome + File.separator + "Downloads");
        File desktopFolder = new File(userHome + File.separator + "Desktop");

        if (downloadsFolder.exists()) {
            this.destinyPath = downloadsFolder.getAbsolutePath();
        } else if (desktopFolder.exists()) {
            this.destinyPath = desktopFolder.getAbsolutePath();
        } else {
            this.destinyPath = userHome;
        }

        jLabelSave.setText("Saved at: " + this.destinyPath);
        jButtonSavePath.setVisible(false);
        jButtonChange.setVisible(true);

 
        if (token == null || token.isEmpty()) {
            // --- CASO LOGIN ---
            showLoginScreen(); // Este método ahora se encargará de encoger la ventana
        } else {
            // --- CASO MAIN ---
            initMediaPoller(token);
            this.setSize(1024, 330); // Tamaño grande para descargas
            this.setLocationRelativeTo(null);
        }
        updateIconState(this.mediaPoller1.isRunning());
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                String[] options = {"Yes", "No"};
                int result = JOptionPane.showOptionDialog(MainScreen.this,
                        "Are you sure you want to exit?",
                        "Exit", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null,
                        options, options[0]);

                if (result == 0) {
                    com.gomez.yourdownload.service.DownloadService.saveHistory(resourcesList);
                    System.exit(0);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupQuality = new javax.swing.ButtonGroup();
        buttonGroupAQ = new javax.swing.ButtonGroup();
        jLabelWelcome = new javax.swing.JLabel();
        jPanelWeb = new javax.swing.JPanel();
        jLabelUrl = new javax.swing.JLabel();
        jTextFieldUrl = new javax.swing.JTextField();
        jPanelQuality = new javax.swing.JPanel();
        jLabelQuality = new javax.swing.JLabel();
        jRadioButton1080 = new javax.swing.JRadioButton();
        jRadioButton720 = new javax.swing.JRadioButton();
        jRadioButton480 = new javax.swing.JRadioButton();
        jPanelSubtitle = new javax.swing.JPanel();
        jLabelSubtitles = new javax.swing.JLabel();
        jCheckBoxSubtitlesYes = new javax.swing.JCheckBox();
        jPanelFormat = new javax.swing.JPanel();
        jLabelFormat = new javax.swing.JLabel();
        jComboBoxFormat = new javax.swing.JComboBox<>();
        jPanelSave = new javax.swing.JPanel();
        jLabelSave = new javax.swing.JLabel();
        jButtonSavePath = new javax.swing.JButton();
        jButtonChange = new javax.swing.JButton();
        jPanelProgress = new javax.swing.JPanel();
        jLabelProgress = new javax.swing.JLabel();
        jProgressBar = new javax.swing.JProgressBar();
        jPanelConsole = new javax.swing.JPanel();
        jScrollPaneConsole = new javax.swing.JScrollPane();
        jTextAreaConsole = new javax.swing.JTextArea();
        jPanelDownload = new javax.swing.JPanel();
        jButtonDownload = new javax.swing.JButton();
        jPanelLibrary = new javax.swing.JPanel();
        jButtonLibrary = new javax.swing.JButton();
        jPanelAudioQuality = new javax.swing.JPanel();
        jRadioButtonHQ = new javax.swing.JRadioButton();
        jRadioButtonHigh = new javax.swing.JRadioButton();
        jLabelAQ = new javax.swing.JLabel();
        mediaPoller1 = new com.gomez.component.MediaPoller();
        jButtonShowLog = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemPreferences = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YourDownload");
        getContentPane().setLayout(null);

        jLabelWelcome.setText("Welcome! Download videos with no barriers!");
        getContentPane().add(jLabelWelcome);
        jLabelWelcome.setBounds(10, 10, 240, 16);

        jPanelWeb.setLayout(null);

        jLabelUrl.setText("URL site:");
        jPanelWeb.add(jLabelUrl);
        jLabelUrl.setBounds(0, 0, 50, 20);

        jTextFieldUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUrlActionPerformed(evt);
            }
        });
        jPanelWeb.add(jTextFieldUrl);
        jTextFieldUrl.setBounds(110, 0, 670, 30);

        getContentPane().add(jPanelWeb);
        jPanelWeb.setBounds(10, 50, 780, 30);

        jPanelQuality.setLayout(null);

        jLabelQuality.setText("Output Resolution:");
        jPanelQuality.add(jLabelQuality);
        jLabelQuality.setBounds(0, 0, 100, 20);

        buttonGroupQuality.add(jRadioButton1080);
        jRadioButton1080.setText("1080p");
        jRadioButton1080.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1080ActionPerformed(evt);
            }
        });
        jPanelQuality.add(jRadioButton1080);
        jRadioButton1080.setBounds(110, 0, 60, 21);

        buttonGroupQuality.add(jRadioButton720);
        jRadioButton720.setText("720p");
        jRadioButton720.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton720ActionPerformed(evt);
            }
        });
        jPanelQuality.add(jRadioButton720);
        jRadioButton720.setBounds(170, 0, 50, 21);

        buttonGroupQuality.add(jRadioButton480);
        jRadioButton480.setText("480p");
        jPanelQuality.add(jRadioButton480);
        jRadioButton480.setBounds(220, 0, 50, 21);

        getContentPane().add(jPanelQuality);
        jPanelQuality.setBounds(10, 90, 270, 20);

        jPanelSubtitle.setLayout(null);

        jLabelSubtitles.setText("Download Subtitles:");
        jPanelSubtitle.add(jLabelSubtitles);
        jLabelSubtitles.setBounds(0, 0, 110, 20);

        jCheckBoxSubtitlesYes.setText("Yes");
        jCheckBoxSubtitlesYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSubtitlesYesActionPerformed(evt);
            }
        });
        jPanelSubtitle.add(jCheckBoxSubtitlesYes);
        jCheckBoxSubtitlesYes.setBounds(120, 0, 84, 20);

        getContentPane().add(jPanelSubtitle);
        jPanelSubtitle.setBounds(320, 90, 170, 30);

        jPanelFormat.setLayout(null);

        jLabelFormat.setText("Output Format:");
        jPanelFormat.add(jLabelFormat);
        jLabelFormat.setBounds(0, 0, 90, 20);

        jComboBoxFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".mp4", ".avi", ".mp3" }));
        jComboBoxFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFormatActionPerformed(evt);
            }
        });
        jPanelFormat.add(jComboBoxFormat);
        jComboBoxFormat.setBounds(110, 0, 72, 22);

        getContentPane().add(jPanelFormat);
        jPanelFormat.setBounds(10, 130, 190, 30);

        jPanelSave.setLayout(null);

        jLabelSave.setText("Destination folder:");
        jPanelSave.add(jLabelSave);
        jLabelSave.setBounds(0, 0, 260, 20);

        jButtonSavePath.setText("Choose save location");
        jButtonSavePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSavePathActionPerformed(evt);
            }
        });
        jPanelSave.add(jButtonSavePath);
        jButtonSavePath.setBounds(110, 0, 150, 20);

        jButtonChange.setText("Change");
        jButtonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeActionPerformed(evt);
            }
        });
        jPanelSave.add(jButtonChange);
        jButtonChange.setBounds(270, 0, 72, 20);

        getContentPane().add(jPanelSave);
        jPanelSave.setBounds(10, 170, 440, 20);

        jPanelProgress.setLayout(null);

        jLabelProgress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelProgress.setText("Completed:");
        jPanelProgress.add(jLabelProgress);
        jLabelProgress.setBounds(0, -10, 100, 40);
        jPanelProgress.add(jProgressBar);
        jProgressBar.setBounds(110, 0, 670, 20);

        getContentPane().add(jPanelProgress);
        jPanelProgress.setBounds(10, 210, 780, 30);

        jPanelConsole.setLayout(null);

        jTextAreaConsole.setColumns(20);
        jTextAreaConsole.setRows(5);
        jScrollPaneConsole.setViewportView(jTextAreaConsole);

        jPanelConsole.add(jScrollPaneConsole);
        jScrollPaneConsole.setBounds(0, 0, 990, 430);

        getContentPane().add(jPanelConsole);
        jPanelConsole.setBounds(10, 280, 990, 460);

        jPanelDownload.setLayout(null);

        jButtonDownload.setText("Download!");
        jButtonDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownloadActionPerformed(evt);
            }
        });
        jPanelDownload.add(jButtonDownload);
        jButtonDownload.setBounds(0, 0, 170, 60);

        getContentPane().add(jPanelDownload);
        jPanelDownload.setBounds(830, 40, 170, 60);

        jPanelLibrary.setLayout(null);

        jButtonLibrary.setText("Media Library");
        jButtonLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLibraryActionPerformed(evt);
            }
        });
        jPanelLibrary.add(jButtonLibrary);
        jButtonLibrary.setBounds(0, 0, 170, 60);

        getContentPane().add(jPanelLibrary);
        jPanelLibrary.setBounds(830, 110, 170, 60);

        jPanelAudioQuality.setLayout(null);

        buttonGroupAQ.add(jRadioButtonHQ);
        jRadioButtonHQ.setText("HQ (Best)");
        jRadioButtonHQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHQActionPerformed(evt);
            }
        });
        jPanelAudioQuality.add(jRadioButtonHQ);
        jRadioButtonHQ.setBounds(50, 0, 100, 21);

        buttonGroupAQ.add(jRadioButtonHigh);
        jRadioButtonHigh.setText("Balanced (High)");
        jRadioButtonHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHighActionPerformed(evt);
            }
        });
        jPanelAudioQuality.add(jRadioButtonHigh);
        jRadioButtonHigh.setBounds(140, 0, 120, 21);

        jLabelAQ.setText("Audio:");
        jPanelAudioQuality.add(jLabelAQ);
        jLabelAQ.setBounds(0, 0, 80, 20);

        getContentPane().add(jPanelAudioQuality);
        jPanelAudioQuality.setBounds(10, 90, 270, 20);

        mediaPoller1.setApiUrl("https://difreenet9.azurewebsites.net");
        getContentPane().add(mediaPoller1);
        mediaPoller1.setBounds(310, 10, 150, 18);

        jButtonShowLog.setText("Show Log Details");
        jButtonShowLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowLogActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShowLog);
        jButtonShowLog.setBounds(10, 240, 130, 23);

        jLabelStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelStatusMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelStatus);
        jLabelStatus.setBounds(980, 10, 0, 0);

        jMenuFile.setText("File");

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemLogout);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar.add(jMenuFile);

        jMenuEdit.setText("Edit");

        jMenuItemPreferences.setText("Preferences");
        jMenuItemPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPreferencesActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemPreferences);

        jMenuBar.add(jMenuEdit);

        jMenuHelp.setText("Help");

        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar.add(jMenuHelp);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUrlActionPerformed

    private void jRadioButton1080ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1080ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1080ActionPerformed

    private void jCheckBoxSubtitlesYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSubtitlesYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSubtitlesYesActionPerformed

    private void jButtonSavePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSavePathActionPerformed
        // Filechooser para seleccionar una ruta
        JFileChooser pathSelector = new JFileChooser();
        pathSelector.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int result = pathSelector.showOpenDialog(this); // selecciona la ruta 
        if (result == JFileChooser.APPROVE_OPTION) {
            File folder = pathSelector.getSelectedFile();
            destinyPath = folder.getAbsolutePath();

            jLabelSave.setText("Saved at: " + destinyPath);

            jButtonSavePath.setVisible(false);
            jButtonChange.setVisible(true);
        }
    }//GEN-LAST:event_jButtonSavePathActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        String[] options = {"Yes", "No"};
        int result = JOptionPane.showOptionDialog(this, "Are you sure you want to exit?",
                "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                options, options[0]);

        if (result == 0) {
            DownloadService.saveHistory(resourcesList);
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        About dialog = new About(this, true); // 'this' es tu JFrame principal
        dialog.setLocationRelativeTo(this); // Centrado respecto a la ventana principal
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItemPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPreferencesActionPerformed
        javax.swing.JPanel currentPanel = (javax.swing.JPanel) this.getContentPane();
        setContentPane(new PreferencesPanel(this, currentPanel));

        revalidate();
        repaint();
    }//GEN-LAST:event_jMenuItemPreferencesActionPerformed

    private void jButtonDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownloadActionPerformed
        final String url = jTextFieldUrl.getText().trim(); // Le indicamos que coja el texto del TextField

        if (url.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduce una URL válida"); //En caso de que no se introduzca una URL correcta.
            return;
        }

        jButtonDownload.setEnabled(false);
        jTextAreaConsole.setText("");
        jProgressBar.setValue(0);

        // Asignar calidad al video. Simple IF para escoger la calidad. 
        String selectedFormat = "bestvideo+bestaudio"; // Default: la mejor calidad disponible

        if (jRadioButton1080.isSelected()) {
            // Busca el mejor video de 1080p o menos, más el mejor audio
            selectedFormat = "bestvideo[height<=1080]+bestaudio";
        } else if (jRadioButton720.isSelected()) {
            // Busca el mejor video de 720p o menos, más el mejor audio
            selectedFormat = "bestvideo[height<=720]+bestaudio";
        } else if (jRadioButton480.isSelected()) {
            // Busca el mejor video de 480p o menos, más el mejor audio
            selectedFormat = "bestvideo[height<=480]+bestaudio";
        }

        // El resto del código que usa 'finalFormat' permanece igual
        boolean downloadSubtitle = jCheckBoxSubtitlesYes.isSelected();
        final String finalFormat = selectedFormat; // Igualamos a selectedFormat ya que el uso de Thread no permite el cambio de la variable que debe ser final.

        new Thread(() -> {

            final File[] downloadFile = new File[1];
            try {

                // 1. LLAMAR AL SERVICIO DE RUTAS (MVC)
                String binariesPath = getBinariesPath();

                if (binariesPath.isEmpty() || !new File(binariesPath).exists()) {
                    SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(this,
                                "yt-dlp.exe not found at:\n" + binariesPath + "\nPlease check Preferences.",
                                "Config error", JOptionPane.ERROR_MESSAGE);
                    });
                    return; // Detenemos el hilo aquí
                }
                String binariesPathNormalized = binariesPath.replace(File.separator, "/");
                List<String> command = new ArrayList<>();
                command.add(binariesPathNormalized);
                command.add("--force-overwrites");
                command.add("--restrict-filenames");
                String outputFormat = jComboBoxFormat.getSelectedItem().toString();

                if (outputFormat.contains(".mp3")) {
                    // no se especifica -f para audio
                    command.add("-x");
                    command.add("--audio-format");
                    command.add("mp3");

                    String audioQuality = "best";

                    if (jRadioButtonHQ.isSelected()) {
                        audioQuality = "0";
                    } else if (jRadioButtonHigh.isSelected()) {
                        audioQuality = "5";
                    }

                    if (!audioQuality.equals("best")) {
                        command.add("--audio-quality");
                        command.add(audioQuality);
                    }

                } else {
                    // se especifica -f 
                    command.add("-f");
                    command.add(finalFormat);

                    if (outputFormat.contains(".mp4")) {
                        command.add("--recode-video");
                        command.add("mp4");
                    } else if (outputFormat.contains(".avi")) {
                        command.add("--recode-video");
                        command.add("avi");
                    }
                }
                if (!destinyPath.isEmpty()) {
                    command.add("-o");
                    String destinyPathNormalized = destinyPath.replace(File.separator, "/"); // Normalizar destino
                    command.add(destinyPathNormalized + File.separator + "%(title)s - %(epoch)s.%(ext)s");
                }

                command.add(url);

                if (downloadSubtitle) {
                    command.add("--write-auto-sub");       // descarga subtítulos
                    command.add("--sub-lang");
                    command.add("en");                // idioma español
                    command.add("--convert-subs");
                    command.add("srt");               // formato .srt
                }

                System.out.println("Comando final: " + String.join(" ", command));
                ProcessBuilder builder = new ProcessBuilder(command); // Añadimos -f para que seleccione formato.
                builder.redirectErrorStream(true);
                Process process = builder.start();

                BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                String line;
                while ((line = reader.readLine()) != null) {
                    final String outputLine = line;
                    if (outputLine.contains("Destination:")) {
                        String path = outputLine.substring(outputLine.indexOf("Destination:") + 12).trim();
                        downloadFile[0] = new File(path);
                        System.out.println("Archivo detectado (Destination): " + path);
                    } else if (outputLine.contains("Merging formats into")) {
                        String path = outputLine.substring(outputLine.indexOf("Merging formats into") + 22).trim().replaceAll("\"", "");
                        downloadFile[0] = new File(path);
                        System.out.println("Archivo detectado (Merge): " + path);
                    } else if (outputLine.contains("Deleting original file") && downloadFile[0] == null) {
                        // En caso de que se haya convertido y el original se haya eliminado
                        int start = outputLine.indexOf("Deleting original file") + 25;
                        int end = outputLine.lastIndexOf("\"");
                        if (start < end) {
                            String path = outputLine.substring(start, end).trim().replaceAll("\"", "");
                            downloadFile[0] = new File(path);
                            System.out.println("Archivo detectado (Deleted original): " + path);
                        }
                    }

                    SwingUtilities.invokeLater(() -> {
                        jTextAreaConsole.append(outputLine + "\n");
                        jTextAreaConsole.setCaretPosition(jTextAreaConsole.getDocument().getLength());
                        updateProgressBar(outputLine);
                    });
                }
                process.waitFor();
            } catch (IOException | InterruptedException e) {
                SwingUtilities.invokeLater(() -> jTextAreaConsole.append("Error: " + e.getMessage() + "\n"));
            } finally {
                SwingUtilities.invokeLater(() -> {
                    jButtonDownload.setEnabled(true);

                    // CORRECCIÓN DEL NULL POINTER EXCEPTION
                    File finalFile = downloadFile[0];

                    if (finalFile != null && finalFile.exists()) {
                        System.out.println("DEBUG: File found: " + finalFile.getAbsolutePath());

                        // Añadir al historial
                        String absolutePath = finalFile.getAbsolutePath();
                        long size = finalFile.length();
                        String mimeType = obtainMimeSimple(finalFile.getName());
                        DownloadInfo newDownload = new DownloadInfo(absolutePath, new Date(), size, mimeType);
                        resourcesList.add(newDownload);

                        // Abrir diálogo
                        DownloadComplete dialog = new DownloadComplete(null, true, finalFile);
                        dialog.setSize(300, 250);
                        dialog.setLocationRelativeTo(null);
                        dialog.setVisible(true);
                    } else {
                        // 2. Lógica de fallo (Evita el crash)
                        // Si llegamos aquí, yt-dlp falló silenciosamente o no se parseó la salida.
                        JOptionPane.showMessageDialog(this,
                                "The download process finished, but the file was not detected.\nCheck the console for errors.",
                                "Download Error", JOptionPane.WARNING_MESSAGE);
                    }
                });
            }
        }).start();
    }//GEN-LAST:event_jButtonDownloadActionPerformed

    private void jComboBoxFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFormatActionPerformed
        // 1. Obtener el formato seleccionado (ej: ".mp3" o ".mp4")
        String outputFormat = jComboBoxFormat.getSelectedItem().toString();

        // 2. Comprobar si es audio
        boolean isAudio = outputFormat.contains(".mp3");
        jPanelAudioQuality.setVisible(isAudio);
        jPanelQuality.setVisible(!isAudio);

        if (isAudio) {
            buttonGroupQuality.clearSelection();
        } else {
            buttonGroupAQ.clearSelection();
        }

    }//GEN-LAST:event_jComboBoxFormatActionPerformed

    private void jButtonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeActionPerformed
        JFileChooser pathSelector = new JFileChooser();
        pathSelector.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int result = pathSelector.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File folder = pathSelector.getSelectedFile();
            destinyPath = folder.getAbsolutePath();

            jLabelSave.setText("Saved at: " + destinyPath);
            // No necesitas cambiar visibilidad aquí
        }
    }//GEN-LAST:event_jButtonChangeActionPerformed

    private void jButtonLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLibraryActionPerformed
        showLibrary();
    }//GEN-LAST:event_jButtonLibraryActionPerformed

    private void jRadioButton720ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton720ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton720ActionPerformed

    private void jRadioButtonHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonHighActionPerformed

    private void jRadioButtonHQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonHQActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
// 1. Borrar la persistencia de la sesión
        java.util.prefs.Preferences prefs = java.util.prefs.Preferences.userRoot().node("YourDownloadApp");
        prefs.remove("jwt_token");
        prefs.remove("email");

        // 2. EN LUGAR DE CERRAR, CAMBIAMOS EL PANEL
        // No hagas dispose(). Simplemente muestra el panel de login.
        showLoginScreen();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jButtonShowLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowLogActionPerformed

        if (!jPanelConsole.isVisible()) {
            // MODO DETALLADO: Mostramos consola y agrandamos ventana
            jPanelConsole.setVisible(true);
            this.setSize(1024, 800);
            jButtonShowLog.setText("Hide Details");
        } else {
            // MODO COMPACTO: Ocultamos consola y encogemos ventana
            jPanelConsole.setVisible(false);
            this.setSize(1024, 330);
            jButtonShowLog.setText("Show Details");
        }

        // Refrescamos la UI para que los cambios se apliquen visualmente
        this.revalidate();
        this.repaint(); // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShowLogActionPerformed

    private void jLabelStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStatusMouseClicked
        togglePolling();// TODO add your handling code here:
    }//GEN-LAST:event_jLabelStatusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Al quitar el 'scope' del pom.xml, esto ya no saldrá en rojo
            com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (Exception ex) {
            System.err.println("Error al cargar el tema moderno");
        }

        // 2. Ejecución de la aplicación
        java.awt.EventQueue.invokeLater(() -> {
            // Obtenemos el token guardado
            java.util.prefs.Preferences prefs = java.util.prefs.Preferences.userRoot().node("YourDownloadApp");
            String token = prefs.get("jwt_token", null);

            // CREACIÓN DEL POLLER (Asegúrate de que el nombre de la clase coincida con tu componente)
            com.gomez.component.MediaPoller globalPoller = new com.gomez.component.MediaPoller();
            globalPoller.setApiUrl("https://difreenet9.azurewebsites.net/");

            // Abrimos la pantalla principal
            new MainScreen(token, globalPoller).setVisible(true);
        });
    }

    private void updateProgressBar(String line) {
        Pattern pattern = Pattern.compile("\\[download\\]\\s+(\\d+\\.\\d+)%");
        Matcher matcher = pattern.matcher(line);
        if (matcher.find()) {
            double percent = Double.parseDouble(matcher.group(1));
            jProgressBar.setValue((int) percent);
        }
    }

    /**
     * Determina un tipo MIME (formato de contenido) simple basado en la
     * extensión del archivo. * Esta función es auxiliar para categorizar el
     * archivo descargado (MP4, AVI, MP3) para la biblioteca.
     *
     * @param fileName El nombre completo del archivo (e.g., "MiVideo.mp4").
     * @return El String que representa el tipo MIME estándar (e.g.,
     * "video/mp4").
     */
    private String obtainMimeSimple(String fileName) {
        if (fileName.toLowerCase().endsWith(".mp4")) {
            return "video/mp4";
        } else if (fileName.toLowerCase().endsWith(".avi")) {
            return "video/x-msvideo";
        } else if (fileName.toLowerCase().endsWith(".mp3")) {
            return "audio/mpeg";
        }
        return "application/octet-stream";
    }

    private String getBinariesPath() {
        Preferences prefs = Preferences.userRoot().node("PreferencesPanel");
        final String PREFS_KEY = "binariesPath";

        String storedPath = prefs.get(PREFS_KEY, "");
        if (!storedPath.isEmpty() && new File(storedPath).exists()) {
            return storedPath; // ¡La configuración manual funciona!
        }

        String localAppData = System.getenv("LOCALAPPDATA");
        if (localAppData != null && !localAppData.isEmpty()) {
            String appDataPath = localAppData + File.separator + "yt-dlp.exe";
            if (new File(appDataPath).exists()) {
                prefs.put(PREFS_KEY, appDataPath);
                return appDataPath;
            }
        }

        String userHomePath = System.getProperty("user.home") + File.separator + "yt-dlp.exe";
        if (new File(userHomePath).exists()) {
            prefs.put(PREFS_KEY, userHomePath);
            return userHomePath;
        }
        return "";
    }

    private void showLibrary() {
        this.currentView = "LIBRARY"; // Guardamos que estamos en la librería
        this.setSize(1024, 600);
        this.setLocationRelativeTo(null);
        MediaLibrary libraryPanel = new MediaLibrary(this, originalPanel, resourcesList, this.mediaPoller1);
        setContentPane(libraryPanel);
        revalidate();
        repaint();
    }

    private void initMediaPoller(String token) {
        if (this.mediaPoller1 == null) {
            System.err.println("Mediapoller is null");
            return;
        }

        if (token != null && !token.isEmpty()) {
            this.mediaPoller1.setToken(token);
        }

        this.mediaPoller1.setRunning(true);
        this.mediaPoller1.addNewMediaListener(new com.gomez.component.NewMediaListener() {
            @Override
            public void onNewMediaDetected(com.gomez.component.NewMediaEvent event) {
                handleNewFilesFound(event);
            }
        });
        mediaPoller1.setSize(0, 0);
        updateIconState(this.mediaPoller1.isRunning());
    }

    private void handleNewFilesFound(final com.gomez.component.NewMediaEvent event) {
        //Solo archivos que no están en la biblioteca local
        List<com.gomez.model.Media> trulyNewFiles = new ArrayList<>();

        for (com.gomez.model.Media remoteFile : event.getNewFiles()) {
            // Comprobamos si el archivo ya existe en nuestra lista
            boolean alreadyExists = resourcesList.stream().anyMatch(local
                    -> (local.getNetworkId() != null && local.getNetworkId().equals(remoteFile.id))
                    || (local.getFileName() != null && local.getFileName().equalsIgnoreCase(remoteFile.mediaFileName))
            );

            if (!alreadyExists) {
                trulyNewFiles.add(remoteFile);
            }
        }

        // Si después de filtrar no queda nada nuevo, salimos silenciosamente
        if (trulyNewFiles.isEmpty()) {
            return;
        }

        //LOG DE DETECCIÓN REAL-TIME
        int newCount = trulyNewFiles.size();
        String firstFileName = trulyNewFiles.get(0).mediaFileName;
        System.out.println("Poller (Real-time): detected [" + newCount + "] new files since last check.");

        // 3. ALERTA DE INTERFAZ (Swing Thread)
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                Object[] options = {"Download", "Close"};
                int result = javax.swing.JOptionPane.showOptionDialog(
                        MainScreen.this,
                        "New files detected on server!"
                        + "\nFile: " + firstFileName
                        + "\nDo you want to download them now?",
                        "Live Detection",
                        javax.swing.JOptionPane.YES_NO_OPTION,
                        javax.swing.JOptionPane.INFORMATION_MESSAGE,
                        null, options, options[0]
                );

                if (result == 0) {
                    // 4. HILO DE DESCARGA
                    new Thread(new Runnable() {
                        @Override
                        public void run() {
                            int successCount = 0;
                            for (com.gomez.model.Media mediaFile : trulyNewFiles) {
                                try {
                                    java.io.File destination = new java.io.File(destinyPath, mediaFile.mediaFileName);
                                    mediaPoller1.download(mediaFile.id, destination);

                                    com.gomez.yourdownload.model.DownloadInfo newDownload = new com.gomez.yourdownload.model.DownloadInfo(
                                            destination.getAbsolutePath(),
                                            new java.util.Date(),
                                            destination.length(),
                                            mediaFile.mediaMimeType
                                    );
                                    newDownload.setNetworkId(mediaFile.id);
                                    newDownload.setIsInNetwork(true);

                                    resourcesList.add(newDownload);
                                    successCount++;
                                } catch (Exception e) {
                                    System.err.println("Download error: " + e.getMessage());
                                }
                            }

                            if (successCount > 0) {
                                com.gomez.yourdownload.service.DownloadService.saveHistory(resourcesList);
                                final int finalSuccess = successCount;
                                javax.swing.SwingUtilities.invokeLater(() -> {
                                    showLibrary();
                                    javax.swing.JOptionPane.showMessageDialog(MainScreen.this,
                                            "Added " + finalSuccess + " files from server.");
                                });
                            }
                        }
                    }).start();
                } else {
                    /* * SOLUCIÓN AL SOLAPAMIENTO: Si el usuario cierra el aviso sin descargar, 
                 * añadimos los archivos a la lista como "Cloud Only" para que el Poller 
                 * no vuelva a avisar de ellos en la próxima vuelta de 30 segundos.
                     */
                    for (com.gomez.model.Media m : trulyNewFiles) {
                        com.gomez.yourdownload.model.DownloadInfo acknowledged = new com.gomez.yourdownload.model.DownloadInfo(
                                m.id, m.mediaFileName, (long) m.mediaFileSize, m.mediaMimeType
                        );
                        resourcesList.add(acknowledged);
                    }
                    System.out.println("Poller: Files acknowledged but ignored by user.");
                }
            }
        });
    }

    private void showLoginScreen() {
        this.setJMenuBar(null);
        this.setResizable(false);
        LoginPanel login = new LoginPanel(this, this.mediaPoller1);
        this.setContentPane(login);
        this.setSize(500, 320);
        this.setLocationRelativeTo(null);
        this.revalidate();
        this.repaint();
    }

    public void loginSuccessful(String token) { // Si se pone bien la contraseña llama a este método
        this.jwtToken = token;

        //Restauramos el diseño original
        this.setJMenuBar(jMenuBar);
        this.setContentPane(originalPanel);
        jPanelConsole.setVisible(false);
        this.setSize(1024, 330);
        this.setLocationRelativeTo(null);
        this.revalidate();
        this.repaint();
        initMediaPoller(token);
    }

    private void togglePolling() {
        boolean running = this.mediaPoller1.isRunning();

        boolean newState = !running;
        this.mediaPoller1.setRunning(newState);

        updateIconState(newState);

        System.out.println("Poller changed to: " + (newState ? "On" : "Off"));
    }

    private void updateIconState(boolean on) {
        String iconPath = on ? "/icons/status_on.png" : "/icons/status_off.png";
        try {
            java.net.URL imgURL = getClass().getResource(iconPath);
            if (imgURL != null) {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
                jLabelStatus.setIcon(icon);

                jLabelStatus.setSize(24, 24);
                jLabelStatus.setBounds(960, 10, 24, 24);

                jLabelStatus.setToolTipText(on ? "Server Sync: ACTIVE" : "Server Sync: STOPPED");
                jLabelStatus.setText("");
            }
        } catch (Exception e) {
            jLabelStatus.setText(on ? "V" : "X");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAQ;
    private javax.swing.ButtonGroup buttonGroupQuality;
    private javax.swing.JButton jButtonChange;
    private javax.swing.JButton jButtonDownload;
    private javax.swing.JButton jButtonLibrary;
    private javax.swing.JButton jButtonSavePath;
    private javax.swing.JButton jButtonShowLog;
    private javax.swing.JCheckBox jCheckBoxSubtitlesYes;
    private javax.swing.JComboBox<String> jComboBoxFormat;
    private javax.swing.JLabel jLabelAQ;
    private javax.swing.JLabel jLabelFormat;
    private javax.swing.JLabel jLabelProgress;
    private javax.swing.JLabel jLabelQuality;
    private javax.swing.JLabel jLabelSave;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelSubtitles;
    private javax.swing.JLabel jLabelUrl;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemPreferences;
    private javax.swing.JPanel jPanelAudioQuality;
    private javax.swing.JPanel jPanelConsole;
    private javax.swing.JPanel jPanelDownload;
    private javax.swing.JPanel jPanelFormat;
    private javax.swing.JPanel jPanelLibrary;
    private javax.swing.JPanel jPanelProgress;
    private javax.swing.JPanel jPanelQuality;
    private javax.swing.JPanel jPanelSave;
    private javax.swing.JPanel jPanelSubtitle;
    private javax.swing.JPanel jPanelWeb;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JRadioButton jRadioButton1080;
    private javax.swing.JRadioButton jRadioButton480;
    private javax.swing.JRadioButton jRadioButton720;
    private javax.swing.JRadioButton jRadioButtonHQ;
    private javax.swing.JRadioButton jRadioButtonHigh;
    private javax.swing.JScrollPane jScrollPaneConsole;
    private javax.swing.JTextArea jTextAreaConsole;
    private javax.swing.JTextField jTextFieldUrl;
    private com.gomez.component.MediaPoller mediaPoller1;
    // End of variables declaration//GEN-END:variables
}
