package com.gomez.yourdownload.view;


import com.gomez.yourdownload.model.DownloadInfoTableModel;
import com.gomez.yourdownload.model.DownloadInfo;
import java.util.List;
import javax.swing.JPanel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author LionKeriot
 */
public class MediaLibrary extends javax.swing.JPanel {
    private final MainScreen principal;
    private final JPanel originalPanel;
    private final List<DownloadInfo> resourcesList;
    private DownloadInfoTableModel tableModel;

    
    public MediaLibrary (MainScreen principal, JPanel originalPanel, List<DownloadInfo> resourcesList){
        this.principal = principal;
        this.originalPanel = originalPanel;
        this.resourcesList = resourcesList;
        
        initComponents();
        tableModel = new DownloadInfoTableModel(resourcesList);
        jTableMedia.setModel(tableModel);
        
        javax.swing.table.TableRowSorter<DownloadInfoTableModel> sorter = new javax.swing.table.TableRowSorter<>(tableModel);
        jTableMedia.setRowSorter(sorter);
        
        
        initFiltroComboBox();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneMedia = new javax.swing.JScrollPane();
        jTableMedia = new javax.swing.JTable();
        jLabelFilter = new javax.swing.JLabel();
        jComboBoxFilter = new javax.swing.JComboBox<>();
        jButtonDelete = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();

        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(937, 371));
        setLayout(null);

        jTableMedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneMedia.setViewportView(jTableMedia);

        add(jScrollPaneMedia);
        jScrollPaneMedia.setBounds(0, 0, 930, 220);

        jLabelFilter.setText("Filter by:");
        add(jLabelFilter);
        jLabelFilter.setBounds(10, 230, 70, 30);

        jComboBoxFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFilterActionPerformed(evt);
            }
        });
        add(jComboBoxFilter);
        jComboBoxFilter.setBounds(130, 230, 120, 30);

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        add(jButtonDelete);
        jButtonDelete.setBounds(400, 230, 120, 30);

        jButtonBack.setText("Return");
        jButtonBack.setName(""); // NOI18N
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        add(jButtonBack);
        jButtonBack.setBounds(690, 230, 120, 30);

        jButtonSearch.setText("Search by text");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        add(jButtonSearch);
        jButtonSearch.setBounds(130, 280, 120, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        principal.setContentPane(originalPanel);
        principal.revalidate();
        principal.repaint();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
       // Obtiene la fila seleccionada
       Object[] options = {"Yes", "No"};
        int selectedRow = jTableMedia.getSelectedRow();
        
        // Asignamos una variable al recurso que vamos a eliminar.
        if (selectedRow >=0) {
            DownloadInfo  resourceDelete = resourcesList.get(selectedRow);
        
       // Pedimos confirmación
       int confirmation = javax.swing.JOptionPane.showOptionDialog(this,"Are you sure you want to delete '" 
            + resourceDelete.getFileName(),"Confirm Deletion",
            javax.swing.JOptionPane.YES_NO_OPTION, // Tipo de opción
            javax.swing.JOptionPane.QUESTION_MESSAGE, // Icono de pregunta
            null, // No usar icono custom
            options, // Array de Strings a mostrar en los botones
            options[0] // Opción por defecto ("Yes")
            );
       
        if (confirmation == javax.swing.JOptionPane.YES_OPTION) {
            java.io.File file = new java.io.File(resourceDelete.getAbsolutePath());

            if (file.delete()) {
                resourcesList.remove(selectedRow);
                tableModel.fireTableDataChanged();
                javax.swing.JOptionPane.showMessageDialog(this, "File deleted successfully.", "Success!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } else {
                    // Error al eliminar del disco (ej: el archivo no existe o permisos insuficientes)
                    javax.swing.JOptionPane.showMessageDialog(this, "Error: File could not have been deleted. Check the log.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
            } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a file to delete", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jComboBoxFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFilterActionPerformed

    
    @SuppressWarnings("unchecked")
    javax.swing.table.TableRowSorter<DownloadInfoTableModel> sorter = 
    (javax.swing.table.TableRowSorter<DownloadInfoTableModel>) jTableMedia.getRowSorter();
    
        if (sorter == null) return; 
        String selectedFilter = (String) jComboBoxFilter.getSelectedItem();
    
        if (selectedFilter.equals("All Types")) {
            // CASO A: Mostrar todas las filas.
            sorter.setRowFilter(null); 
        } else {
        // CASO B: Filtrar las filas (el caso que antes estaba en el 'else').
        String mimeTypeFilter = "";
        // Lógica de traducción
        if (selectedFilter.contains("MP4")) {
            mimeTypeFilter = "video/mp4";
        } else if (selectedFilter.contains("AVI")) {
            mimeTypeFilter = "video/x-msvideo";
        } else if (selectedFilter.contains("MP3")) {
            mimeTypeFilter = "audio/mpeg";
        }
        
        // Aplicar el filtro a la Columna 2 (MIME Type)
        javax.swing.RowFilter<Object, Object> rf = 
            javax.swing.RowFilter.regexFilter("^" + mimeTypeFilter + "$", 2);
            
        sorter.setRowFilter(rf);
    }
    }//GEN-LAST:event_jComboBoxFilterActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        javax.swing.JFrame parentFrame = principal;
    
    try {
        // La ejecución crítica que puede fallar:
        SearchDialog search = new SearchDialog(parentFrame, resourcesList);
        search.setVisible(true);
        
    } catch (Exception e) {
        // Capturamos la excepción (NPE, error de componente, etc.)
        javax.swing.JOptionPane.showMessageDialog(principal, 
            "Error opening search: " + e.getMessage(), 
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        
        // Esta línea es crucial para ver la traza de error completa en la consola
        e.printStackTrace(); 
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void initFiltroComboBox() {
        // 1. Definimos las opciones de filtro con nombres amigables para el usuario
        String[] filterTypes = {
            "All Types",      // Opción 0: Desactivar filtro
            "Video (MP4)",    // Opción para buscar "video/mp4"
            "Audio (MP3)",    // Opción para buscar "audio/mpeg"
            "Video (AVI)"     // Opción para buscar "video/x-msvideo"
        };

        // 2. Asignamos las opciones al JComboBox
        javax.swing.DefaultComboBoxModel<String> filterModel = new javax.swing.DefaultComboBoxModel<>(filterTypes);
        jComboBoxFilter.setModel(filterModel); 
    
        // 3. Conectamos el JComboBox a la lógica de acción
        jComboBoxFilter.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            // Llama al método que contiene la lógica del RowFilter
            jComboBoxFilterActionPerformed(evt);
        }
    });
}

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox<String> jComboBoxFilter;
    private javax.swing.JLabel jLabelFilter;
    private javax.swing.JScrollPane jScrollPaneMedia;
    private javax.swing.JTable jTableMedia;
    // End of variables declaration//GEN-END:variables
}
