package com.gomez.yourdownload.view;


import java.io.File;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author LionKeriot
 */
public class PreferencesPanel extends javax.swing.JPanel {
    
    private JFrame mainScreen;
    private JPanel originalPanel;
    private String destinyPath = "";
    private String binariesPath;
    /**
    *
    * @param mainScreen la ventana principal que contiene este panel
    */

    public PreferencesPanel(JFrame mainScreen, JPanel originalPanel) {
        initComponents();
        this.mainScreen = mainScreen;
        this.originalPanel = originalPanel;
        
        Preferences prefs = Preferences.userRoot().node(this.getClass().getName());
        this.binariesPath = prefs.get("rutaBinarios", "C:\\Users\\ruben\\AppData\\Local\\yt-dlp.exe");
        jLabelBinaries.setText("Binaries path: " + binariesPath);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTemporaly = new javax.swing.JPanel();
        jLabelTemporaly = new javax.swing.JLabel();
        jButtonTemporaly = new javax.swing.JButton();
        jPanelPlaylists = new javax.swing.JPanel();
        jLabelPlaylists = new javax.swing.JLabel();
        jCheckBoxPlaylists = new javax.swing.JCheckBox();
        jPanelLimit = new javax.swing.JPanel();
        jLabelLimit = new javax.swing.JLabel();
        jComboBoxLimit = new javax.swing.JComboBox<>();
        jPanelBinaries = new javax.swing.JPanel();
        jLabelBinaries = new javax.swing.JLabel();
        jButtonBinaries = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        jPanelTemporaly.setLayout(null);

        jLabelTemporaly.setText("Temporary files path:");
        jPanelTemporaly.add(jLabelTemporaly);
        jLabelTemporaly.setBounds(0, 0, 320, 20);

        jButtonTemporaly.setText("Choose");
        jButtonTemporaly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTemporalyActionPerformed(evt);
            }
        });
        jPanelTemporaly.add(jButtonTemporaly);
        jButtonTemporaly.setBounds(430, 0, 75, 23);

        add(jPanelTemporaly);
        jPanelTemporaly.setBounds(10, 20, 650, 30);

        jPanelPlaylists.setLayout(null);

        jLabelPlaylists.setText("Create m3u file for Playlists:");
        jPanelPlaylists.add(jLabelPlaylists);
        jLabelPlaylists.setBounds(0, 0, 146, 20);

        jCheckBoxPlaylists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPlaylistsActionPerformed(evt);
            }
        });
        jPanelPlaylists.add(jCheckBoxPlaylists);
        jCheckBoxPlaylists.setBounds(430, 0, 20, 20);

        add(jPanelPlaylists);
        jPanelPlaylists.setBounds(10, 60, 580, 20);

        jPanelLimit.setLayout(null);

        jLabelLimit.setText("Limit download speed:");
        jPanelLimit.add(jLabelLimit);
        jLabelLimit.setBounds(0, 0, 130, 20);

        jComboBoxLimit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unlimited", "100 MB/s", "10 MB/s", "1 MB/s", " " }));
        jComboBoxLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLimitActionPerformed(evt);
            }
        });
        jPanelLimit.add(jComboBoxLimit);
        jComboBoxLimit.setBounds(430, 0, 100, 22);

        add(jPanelLimit);
        jPanelLimit.setBounds(10, 100, 640, 30);

        jPanelBinaries.setLayout(null);

        jLabelBinaries.setText("Binaries path:");
        jPanelBinaries.add(jLabelBinaries);
        jLabelBinaries.setBounds(0, 0, 380, 20);

        jButtonBinaries.setText("Change Binaries Path");
        jButtonBinaries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBinariesActionPerformed(evt);
            }
        });
        jPanelBinaries.add(jButtonBinaries);
        jButtonBinaries.setBounds(430, 0, 150, 20);

        add(jPanelBinaries);
        jPanelBinaries.setBounds(10, 140, 830, 30);

        jButtonBack.setText("Go back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        add(jButtonBack);
        jButtonBack.setBounds(10, 180, 73, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTemporalyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTemporalyActionPerformed
    JFileChooser chooser = new JFileChooser();
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

    int result = chooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFolder = chooser.getSelectedFile();
        String temporalPath = selectedFolder.getAbsolutePath();

    // Guarda la ruta donde quieras
    jLabelTemporaly.setText(temporalPath); // ejemplo visual
    this.destinyPath = temporalPath;     // ejemplo funcional
}

    
    }//GEN-LAST:event_jButtonTemporalyActionPerformed

    private void jCheckBoxPlaylistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPlaylistsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPlaylistsActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        
        mainScreen.setContentPane(originalPanel);
        mainScreen.revalidate();
        mainScreen.repaint();

    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonBinariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBinariesActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = chooser.getSelectedFile();
        binariesPath = selectedFile.getAbsolutePath();

        jLabelBinaries.setText("Binaries path: " + binariesPath);
        Preferences prefs = Preferences.userRoot().node(this.getClass().getName());
        prefs.put("Binaries Path", binariesPath);
        }
    }//GEN-LAST:event_jButtonBinariesActionPerformed

    private void jComboBoxLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLimitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLimitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBinaries;
    private javax.swing.JButton jButtonTemporaly;
    private javax.swing.JCheckBox jCheckBoxPlaylists;
    private javax.swing.JComboBox<String> jComboBoxLimit;
    private javax.swing.JLabel jLabelBinaries;
    private javax.swing.JLabel jLabelLimit;
    private javax.swing.JLabel jLabelPlaylists;
    private javax.swing.JLabel jLabelTemporaly;
    private javax.swing.JPanel jPanelBinaries;
    private javax.swing.JPanel jPanelLimit;
    private javax.swing.JPanel jPanelPlaylists;
    private javax.swing.JPanel jPanelTemporaly;
    // End of variables declaration//GEN-END:variables
}
