package com.gomez.yourdownload.view;

import java.io.File;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author LionKeriot
 */
public class PreferencesPanel extends javax.swing.JPanel {

    private JFrame mainScreen;
    private JPanel originalPanel;
    private String destinyPath = "";
    private String binariesPath;
    private String tempPath;

    /**
     *
     * @param mainScreen la ventana principal que contiene este panel
     */
    public PreferencesPanel(JFrame mainScreen, JPanel originalPanel) {
        initComponents();
        this.mainScreen = mainScreen;
        this.originalPanel = originalPanel;

        // 1. APPLY CORPORATE STYLING
        applyCorporateStyles();

        // 2. LOAD SAVED PREFERENCES
        Preferences prefs = Preferences.userRoot().node("PreferencesPanel");

        // Load Binaries
        this.binariesPath = prefs.get("binariesPath", "Not set");
        jLabelBinaries.setText("Binaries path: " + binariesPath);

        // Load Temporary Files
        this.tempPath = prefs.get("tempPath", "Not set");
        jLabelTemporaly.setText("Temporary files path: " + tempPath);

        // Load Speed Limit
        int speedIndex = prefs.getInt("speedLimitIndex", 0);
        jComboBoxLimit.setSelectedIndex(speedIndex);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTemporaly = new javax.swing.JPanel();
        jLabelTemporaly = new javax.swing.JLabel();
        jButtonTemporaly = new javax.swing.JButton();
        jPanelPlaylists = new javax.swing.JPanel();
        jLabelPlaylists = new javax.swing.JLabel();
        jCheckBoxPlaylists = new javax.swing.JCheckBox();
        jPanelLimit = new javax.swing.JPanel();
        jLabelLimit = new javax.swing.JLabel();
        jComboBoxLimit = new javax.swing.JComboBox<>();
        jPanelBinaries = new javax.swing.JPanel();
        jLabelBinaries = new javax.swing.JLabel();
        jButtonBinaries = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        jPanelTemporaly.setLayout(null);

        jLabelTemporaly.setText("Temporary files path:");
        jPanelTemporaly.add(jLabelTemporaly);
        jLabelTemporaly.setBounds(0, 0, 320, 20);

        jButtonTemporaly.setText("Choose");
        jButtonTemporaly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTemporalyActionPerformed(evt);
            }
        });
        jPanelTemporaly.add(jButtonTemporaly);
        jButtonTemporaly.setBounds(430, 0, 75, 23);

        add(jPanelTemporaly);
        jPanelTemporaly.setBounds(10, 20, 650, 30);

        jPanelPlaylists.setLayout(null);

        jLabelPlaylists.setText("Create m3u file for Playlists:");
        jPanelPlaylists.add(jLabelPlaylists);
        jLabelPlaylists.setBounds(0, 0, 146, 20);

        jCheckBoxPlaylists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPlaylistsActionPerformed(evt);
            }
        });
        jPanelPlaylists.add(jCheckBoxPlaylists);
        jCheckBoxPlaylists.setBounds(430, 0, 20, 20);

        add(jPanelPlaylists);
        jPanelPlaylists.setBounds(10, 60, 580, 20);

        jPanelLimit.setLayout(null);

        jLabelLimit.setText("Limit download speed:");
        jPanelLimit.add(jLabelLimit);
        jLabelLimit.setBounds(0, 0, 130, 20);

        jComboBoxLimit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unlimited", "100 MB/s", "10 MB/s", "1 MB/s", " " }));
        jComboBoxLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLimitActionPerformed(evt);
            }
        });
        jPanelLimit.add(jComboBoxLimit);
        jComboBoxLimit.setBounds(430, 0, 100, 22);

        add(jPanelLimit);
        jPanelLimit.setBounds(10, 100, 640, 30);

        jPanelBinaries.setLayout(null);

        jLabelBinaries.setText("Binaries path:");
        jPanelBinaries.add(jLabelBinaries);
        jLabelBinaries.setBounds(0, 0, 380, 20);

        jButtonBinaries.setText("Change Binaries Path");
        jButtonBinaries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBinariesActionPerformed(evt);
            }
        });
        jPanelBinaries.add(jButtonBinaries);
        jButtonBinaries.setBounds(430, 0, 150, 20);

        add(jPanelBinaries);
        jPanelBinaries.setBounds(10, 140, 830, 30);

        jButtonBack.setText("Go back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        add(jButtonBack);
        jButtonBack.setBounds(10, 180, 73, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTemporalyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTemporalyActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            tempPath = chooser.getSelectedFile().getAbsolutePath();
            jLabelTemporaly.setText("Temporary files path: " + tempPath);

            Preferences prefs = Preferences.userRoot().node("PreferencesPanel");
            prefs.put("tempPath", tempPath);
            savePrefs(prefs);
        }


    }//GEN-LAST:event_jButtonTemporalyActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed

        mainScreen.setContentPane(originalPanel);
        mainScreen.revalidate();
        mainScreen.repaint();

    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonBinariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBinariesActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            // ... (configuración selector) ...
            if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                File selected = chooser.getSelectedFile();
                if (!selected.exists()) {
                    throw new Exception("Selected file does not exist.");
                }

                binariesPath = selected.getAbsolutePath();
                jLabelBinaries.setText("Binaries path: " + binariesPath);

                Preferences prefs = Preferences.userRoot().node("PreferencesPanel");
                prefs.put("binariesPath", binariesPath);
                savePrefs(prefs);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error selecting binary: " + e.getMessage(), "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBinariesActionPerformed

    private void jComboBoxLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLimitActionPerformed
        Preferences prefs = Preferences.userRoot().node("PreferencesPanel");
        prefs.putInt("speedLimitIndex", jComboBoxLimit.getSelectedIndex());
        savePrefs(prefs);
    }//GEN-LAST:event_jComboBoxLimitActionPerformed

    private void jCheckBoxPlaylistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPlaylistsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPlaylistsActionPerformed
    private void savePrefs(Preferences prefs) {
        try {
            prefs.flush();
        } catch (Exception e) {
            System.err.println("Error guardando preferencias: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                    "No se pudieron guardar las preferencias en el sistema: " + e.getMessage(),
                    "Error de Persistencia",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void applyCorporateStyles() {
        java.awt.Color corporateBlue = new java.awt.Color(74, 134, 173);
        this.setBackground(java.awt.Color.WHITE);

        // Set all internal panels to white background
        javax.swing.JPanel[] subPanels = {
            jPanelTemporaly, jPanelPlaylists, jPanelLimit, jPanelBinaries
        };
        for (javax.swing.JPanel p : subPanels) {
            if (p != null) {
                p.setBackground(java.awt.Color.WHITE);
            }
        }

        // Style Action Buttons (Rectangular & Blue)
        javax.swing.JButton[] actionButtons = {jButtonTemporaly, jButtonBinaries};
        for (javax.swing.JButton btn : actionButtons) {
            if (btn != null) {
                btn.setBackground(corporateBlue);
                btn.setForeground(java.awt.Color.WHITE);
                btn.putClientProperty("JButton.buttonType", "square"); // Rectangular
                btn.putClientProperty("JComponent.arc", 0);            // Zero rounding
                btn.setFocusPainted(false);
                btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }
        }

        // Style Checkbox and ComboBox
        jCheckBoxPlaylists.setBackground(java.awt.Color.WHITE);
        jComboBoxLimit.putClientProperty("JComponent.arc", 0);

        // Convert "Go back" button to Icon
        makeIconOnlyButton(jButtonBack, "/icons/back_blue.png", "Go previous");
        jButtonBack.setBounds(10, 180, 40, 40); // Adjusted for square icon
    }

    private void makeIconOnlyButton(javax.swing.JButton btn, String iconPath, String tooltip) {
        if (btn == null) {
            return;
        }
        btn.setText("");
        btn.setToolTipText(tooltip);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn.setBorderPainted(false);
        btn.setContentAreaFilled(false);
        btn.setFocusPainted(false);
        btn.setOpaque(false);
        try {
            java.net.URL imgURL = getClass().getResource(iconPath);
            if (imgURL != null) {
                // High quality smooth scaling
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
                java.awt.Image scaled = icon.getImage().getScaledInstance(32, 32, java.awt.Image.SCALE_SMOOTH);
                btn.setIcon(new javax.swing.ImageIcon(scaled));
            }
        } catch (Exception e) {
            System.err.println("Icon error: " + iconPath);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBinaries;
    private javax.swing.JButton jButtonTemporaly;
    private javax.swing.JCheckBox jCheckBoxPlaylists;
    private javax.swing.JComboBox<String> jComboBoxLimit;
    private javax.swing.JLabel jLabelBinaries;
    private javax.swing.JLabel jLabelLimit;
    private javax.swing.JLabel jLabelPlaylists;
    private javax.swing.JLabel jLabelTemporaly;
    private javax.swing.JPanel jPanelBinaries;
    private javax.swing.JPanel jPanelLimit;
    private javax.swing.JPanel jPanelPlaylists;
    private javax.swing.JPanel jPanelTemporaly;
    // End of variables declaration//GEN-END:variables
}
